# Dev shells.
#
# Default = nightly so `cargo fuzz run` works out of the box. CI builds
# use stable (rustStable via crate2nix), so if you write nightly-only
# code, checks.clippy-* / checks.nextest-* will catch it.
#
# Use `nix develop .#stable` for strict CI-parity dev.
{
  pkgs,
  rustStable,
  rustNightly,
  sysCrateEnv,
  traceyPkg,
  crate2nixCli,
  # nix/docs.nix — rioTypst (wrapped typst) + typstEnv (TYPST_* vars)
  docsLib,
  shiroaPkg,
  # config.treefmt.build.wrapper — `treefmt` in PATH
  treefmtWrapper,
  # config.pre-commit.installationScript — installs git hooks on shell entry
  preCommitInstall,
  # github:kunobi-ninja/kache — cross-worktree RUSTC_WRAPPER build cache.
  # Consumed via kacheWrapped (policy wrapper: local-only allowlist,
  # pinned config, env-salted store) — never used bare. See kacheWrapped.
  kachePkg,
}:
let
  # nixpkgs still ships sqlx-cli 0.8.6 while the workspace is on sqlx
  # 0.9. `cargo sqlx prepare` must match the library major (it drives
  # the .sqlx/ query cache that sqlx-macros 0.9 consumes, and 0.9
  # changed nullability inference), so pin 0.9.0 here. Feature set
  # mirrors the nixpkgs expression. Drop this override — and the
  # reference below — once nixpkgs ships sqlx-cli ≥ 0.9.
  sqlxCli =
    let
      version = "0.9.0";
      src = pkgs.fetchCrate {
        pname = "sqlx-cli";
        inherit version;
        hash = "sha256-XariusjsCgn0Qai0XWtr7EzSzDDTp1cCzjff1kJNO9Y=";
      };
    in
    pkgs.sqlx-cli.overrideAttrs (_old: {
      inherit version src;
      cargoDeps = pkgs.rustPlatform.fetchCargoVendor {
        inherit src;
        name = "sqlx-cli-${version}-vendor";
        hash = "sha256-pHaMKuB9v3fjbgeVyLyRtfoQ9BkE6z+TjDfdBaVdbXM=";
      };
    });

  # mold-linking stdenv for the dev shells (see the mkShell.override note
  # below). Bound here because kache's store-epoch salt hashes its cc: the
  # cc-wrapper store path moves whenever gcc, mold, bintools, or glibc
  # change — exactly the link inputs kache's cache key cannot see.
  moldStdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.stdenv;

  # kache config, force-pinned via KACHE_CONFIG inside the kacheWrapped
  # script below (the env var short-circuits kache's config search, so a
  # user-level ~/.config/kache/config.toml — possibly holding S3 creds for
  # other projects — can never load here). Two values; everything else
  # matters by ABSENCE: no [cache.remote] and no [cache.planner] sections
  # means kache has nothing to talk to but the local store, and the
  # wrapper's allowlist drops any remote env vars before they could
  # override this file. Per-user knobs: KACHE_DISABLED=1 /
  # RIO_KACHE_MAX_SIZE / RIO_KACHE_CACHE_DIR in .env.local (see
  # .env.local.example; the rio-namespaced ones are mapped inside the
  # wrapper, which deliberately drops kache's own equivalents).
  kacheConfig = pkgs.writeText "kache-config.toml" ''
    # Generated by rio-build's nix/devshell.nix. Local-only on purpose:
    # no [cache.remote], no [cache.planner]. Per-user tuning goes in
    # .env.local — env vars override this file.
    [cache]
    # kache's 50GiB default is sized for one checkout; ~20 sibling
    # worktrees x two toolchains need room. The local store is
    # content-addressed raw blobs, refcount-deduped (zstd applies to
    # remote packs only — verified v0.4.0 src/store.rs).
    local_max_size = "256GiB"
    # Also cache bin crates + nextest harness binaries (kache skips
    # "user-facing executables" by default). This workspace links five
    # fat service bins + 51 test binaries — the critical path of a full
    # build in a fresh worktree is exactly those links, so without this
    # the dep cache halves CPU but barely moves wall-clock. Executables
    # restore by reflink-or-copy (never hardlink, v0.4.0 src/link.rs),
    # and the store epoch is salted by the link environment (see
    # kacheEnvSalt) so a restored binary's PT_INTERP/RPATH always exists.
    cache_executables = true
  '';

  # Salt for the kache store location. kache's key for linked artifacts
  # sees the linker only as the first line of `cc --version` (verified
  # v0.4.0 src/cache_key.rs:1186-1211) — glibc, crt objects, mold, and
  # the cc-wrapper store path are all invisible. After a nixpkgs bump +
  # `nix store gc`, an unsalted store would keep restoring executables /
  # dylibs / proc-macros whose ELF interpreter and RPATH point at GC'd
  # store paths: exec fails with a cryptic ENOENT that `cargo clean`
  # cannot fix (the restore repeats). Hashing the mold-stdenv cc path
  # into the store location makes that impossible by construction — the
  # cc-wrapper derivation rehashes whenever any link input changes, so a
  # toolchain bump is a cold cache, never a dangling interpreter. Old
  # epochs are pruned by the shellHook after 14 days unused.
  # The salt also folds in both rust toolchain store paths: rustc -vV is
  # kache's only toolchain key input, and a toolchain repackaging can
  # rotate the store path while -vV stays byte-identical — restored
  # dylib-class artifacts may reference the old path. Both shells share
  # one wrapper, so both toolchains ride the salt; a nightly-only bump
  # therefore colds the stable epoch too (one rebuild — accepted).
  kacheEnvSalt = builtins.substring 0 12 (
    builtins.hashString "sha256" "${toString moldStdenv.cc}:${toString rustStable}:${toString rustNightly}"
  );

  # Policy wrapper around kache. The policy must live IN THE BINARY:
  # env hygiene done in the shellHook does not survive everything that
  # re-loads user config into a child environment (xtask's dotenvy
  # re-reads .env.local wholesale; IDEs spawn cargo with their own env).
  # Six jobs, numbered in EXECUTION order — the script reads top to
  # bottom (e4d8cb643 let comment order and execution order diverge,
  # and the drift hid a self-scrub bug; keep them in sync):
  #
  #  1. Allowlist scrub, FIRST — the scrub may only ever see inherited
  #     env, never a wrapper-authored export. Every KACHE_* var not
  #     explicitly allowed is dropped — remote knobs AND behavior knobs
  #     (cache_executables, compression, …): the pinned config owns
  #     behavior, and a foreign project's machine-global export must
  #     not steer our store. The allowlist keeps only internal
  #     coordination (KACHE_ACTIVE/KACHE_VERSION — gating those on a
  #     rio sentinel would break build scripts spawning cargo inside a
  #     kache compile; the documented trade is that a rio build
  #     launched from inside ANOTHER project's kache-wrapped build runs
  #     uncached, exotic and fail-open), the opt-out (KACHE_DISABLED),
  #     and output-only logging knobs.
  #  2. Pin the config (KACHE_CONFIG) so kache's config search can
  #     never reach a user-level ~/.config/kache/config.toml.
  #  3. Validate + map the rio-namespaced knobs (policy in the binary —
  #     values arrive via dotenvy/direnv paths that never saw the
  #     shellHook loader). Post-scrub by construction, so the mapped
  #     KACHE_CACHE_DIR/KACHE_MAX_SIZE exports survive to the exec.
  #  4. Store resolution + liveness stamp, BEFORE any bypass so
  #     bypass-heavy sessions (fuzz loops, online checks) stay live for
  #     the prune — stamping gated on KACHE_DISABLED so an opted-out
  #     user's dead store can age out instead of being stamped (and
  #     even mkdir'd) forever.
  #  5. One argv scan: -Z detection plus the sweep coordinates
  #     (--crate-name/--out-dir) feeding sweep_debris (see its comment
  #     for the restore-shape taxonomy and predicate rationale).
  #  6. Routing. Four bypass conditions, every one through the single
  #     run_real() chokepoint (sweep debris, then exec the REAL
  #     compiler — kache never runs on those paths), all
  #     is_compiler-gated so a CLI word can never exec a PATH binary
  #     that happens to share a subcommand's name:
  #      - KACHE_DISABLED truthy by kache's own parse: kache's disabled
  #        mode is pure passthrough with no pre-clean, so without the
  #        sweep a disabled rebuild EACCESes on read-only restores from
  #        earlier enabled runs;
  #      - any -Z argv token → kache cannot key it (v0.4.0 has no -Z
  #        parse arm; RUSTFLAGS-borne flags are keyed via
  #        CARGO_ENCODED_RUSTFLAGS but cargo splices them onto argv
  #        too, so the invariant is route-independent). Watch item: a
  #        future cargo auto-injecting a -Z flag onto argv (the
  #        1.80-era -Zon-broken-pipe incident) would silently bypass
  #        every compile — symptom: `kache stats` counters stop moving.
  #        Gating this arm on is_compiler is a deliberate behavior
  #        change: a -Z-looking token on a CLI invocation now falls
  #        through to kache instead of exec'ing argv blind;
  #      - online-mode sqlx env, by sqlx-macros-core 0.9's OWN
  #        semantics — SQLX_OFFLINE not truthy ("true" any-case or "1",
  #        metadata.rs:160-162) AND DATABASE_URL set non-empty
  #        (query/mod.rs:81-88). DATABASE_URL never reaches a cache key
  #        and RIO_SQLX_HASH still hashes the PRE-regen .sqlx, so
  #        caching would store online-typed artifacts under
  #        offline-looking keys, and a repeat prepare could hit-replay
  #        without the macros ever writing prepare's metadata. Residual
  #        (documented): sqlx also reads these two from .env files,
  #        which the wrapper cannot see;
  #      - no HOME and no override: nowhere sane for a store.
  #     Everything else execs kache — the one exec the job-1 scrub
  #     protects.
  kacheWrapped = pkgs.writeShellApplication {
    name = "kache";
    # sweep_debris's find and job 4's mkdir/touch must come from the
    # wrapper's own closure: the sweep is `2>/dev/null || true`-guarded,
    # so under a spawner with a minimal PATH (IDE-spawned cargo) a
    # missing find would silently no-op the debris sweep and resurrect
    # the EACCES it exists to prevent. Prepending these cannot shadow
    # compiler resolution — neither package ships rustc, clippy-driver,
    # or rustdoc.
    runtimeInputs = with pkgs; [
      findutils
      coreutils
    ];
    text = ''
      # Job 1: allowlist scrub — FIRST, before ANY wrapper export, so it
      # can only ever see inherited env. e4d8cb643 regressed exactly
      # this by reordering: the scrub ran after the wrapper's own
      # KACHE_CACHE_DIR/KACHE_MAX_SIZE exports (neither is allowlisted)
      # and unset them, so every wrapped compile fell back to kache's
      # default unsalted ~/.cache/kache (v0.4.0 config.rs:153-164,
      # precedence env > config > default; the pinned config sets no
      # local_store) — defeating epoch salting and deadening the
      # documented RIO_KACHE_* knobs. Scrub-before-export forecloses
      # the class: no future job reshuffle can make the scrub eat
      # wrapper-authored values. Pure-bash prefix expansion — no
      # externals, nothing that can fail silently inside a process
      # substitution.
      allow=" KACHE_ACTIVE KACHE_VERSION KACHE_DISABLED \
        KACHE_LOG KACHE_LOG_FILE KACHE_LOG_FILE_PATH KACHE_PROGRESS "
      for name in "''${!KACHE_@}"; do
        case "$allow" in
          *" $name "*) ;;
          *) unset "$name" ;;
        esac
      done

      # Job 2: pin the config (post-scrub: an inherited KACHE_CONFIG
      # was just dropped). Short-circuits kache's config search so a
      # user-level ~/.config/kache/config.toml — possibly holding S3
      # creds for other projects — can never load here.
      export KACHE_CONFIG=${kacheConfig}

      # PATH-aware "argv[1] is a runnable compiler" test. cargo passes
      # the BARE name "rustc" (verified empirically with a logging shim
      # on real cargo builds) — a plain [ -x "$1" ] is a CWD-relative
      # pathname test that NEVER fires for cargo-spawned compiles. The
      # bare-name arm is a fixed allowlist (cargo passes rustc;
      # RUSTC_WORKSPACE_WRAPPER chains pass clippy-driver; rustdoc is
      # future-proofing), NOT a blind `command -v` probe: kache CLI
      # words must never satisfy this test, and they CAN collide with
      # PATH binaries. Of v0.4.0's subcommand words (clap enum,
      # main.rs:61-210: list gc purge clean init doctor sync
      # save-manifest daemon monitor stats why-miss report config),
      # `init` and `sync` resolve on this devshell PATH (2026-06-03
      # sweep: init → /run/current-system/sw/bin/init, sync →
      # coreutils) — under a probe-shaped arm, `kache sync` in an
      # online-sqlx env would exec coreutils sync: exit 0 after
      # syncing filesystems, a silent wrong action.
      is_compiler() {
        case "''${1:-}" in
          "") return 1 ;;
          */*) [ -x "$1" ] ;;
          rustc | clippy-driver | rustdoc) command -v "$1" >/dev/null 2>&1 ;;
          *) return 1 ;;
        esac
      }
      # sqlx-macros-core 0.9 is_truthy_bool: "true" (any ASCII case) or
      # exactly "1". Everything else — unset, "", "0", "false", "no" —
      # is NOT offline.
      sqlx_offline_truthy() {
        local v="''${SQLX_OFFLINE:-}"
        [ "''${v,,}" = "true" ] || [ "$v" = "1" ]
      }
      # kache's own opt-out parse — Config::load, v0.4.0
      # config.rs:149-151: disabled iff KACHE_DISABLED is exactly "1"
      # or "true" in any ASCII case; set-but-falsy ("0", "", "false")
      # does NOT disable. (EnvOverrides::detect at config.rs:130 tests
      # mere presence via .is_ok(), but that struct is dead-code-allowed
      # override *tracking*, not behavior — don't "align" this helper
      # to it.)
      kache_disabled() {
        local v="''${KACHE_DISABLED:-}"
        [ "$v" = "1" ] || [ "''${v,,}" = "true" ]
      }

      # Job 3: validate + map the rio-namespaced knobs. Post-scrub by
      # construction, so these exports are the only KACHE_CACHE_DIR/
      # KACHE_MAX_SIZE kache can ever see. The size check is
      # suffix-strip + all-digits, not a `[0-9]*GiB` glob — in a case
      # pattern that glob means "one digit, then ANYTHING" (1.5GiB,
      # '5 GiB' and 1fooGiB all matched while the warning promised
      # <integer><unit>). Strictness matters because kache itself is
      # silent on garbage: KACHE_MAX_SIZE parses via bytesize behind
      # .ok().and_then(parse_size) (v0.4.0 config.rs:166-177,
      # :702-704), so an unparseable value degrades to the pinned
      # config's local_max_size without a word — this warning is the
      # only loud guard.
      if [ -n "''${RIO_KACHE_MAX_SIZE:-}" ]; then
        size_ok=0
        case "$RIO_KACHE_MAX_SIZE" in
          *KiB | *MiB | *GiB | *TiB)
            size_int="''${RIO_KACHE_MAX_SIZE%???}"
            if [ -n "$size_int" ]; then
              case "$size_int" in
                *[!0-9]*) ;;
                *) size_ok=1 ;;
              esac
            fi
            ;;
          *) ;;
        esac
        if [ "$size_ok" = 1 ]; then
          export KACHE_MAX_SIZE="$RIO_KACHE_MAX_SIZE"
        else
          echo "kache wrapper: ignoring RIO_KACHE_MAX_SIZE ($RIO_KACHE_MAX_SIZE) — expected <integer><KiB|MiB|GiB|TiB>, e.g. 512GiB" >&2
        fi
      fi
      if [ -n "''${RIO_KACHE_CACHE_DIR:-}" ]; then
        case "$RIO_KACHE_CACHE_DIR" in
          /*) ;;
          *)
            echo "kache wrapper: ignoring relative RIO_KACHE_CACHE_DIR ($RIO_KACHE_CACHE_DIR) — use an absolute path" >&2
            unset RIO_KACHE_CACHE_DIR
            ;;
        esac
      fi

      # Job 4: store resolution + liveness stamp, BEFORE any bypass so
      # bypass-heavy sessions (fuzz loops, online checks) stay live for
      # the prune. Resolution always runs — CLI invocations under a
      # disabled env still fall through to kache and must see the right
      # store (v0.4.0's CLI ignores the flag for stats/list); only the
      # stamp is gated on KACHE_DISABLED, so a permanently opted-out
      # user's dead store can age out instead of being stamped (and
      # even mkdir'd) forever.
      no_store=0
      if [ -n "''${RIO_KACHE_CACHE_DIR:-}" ]; then
        export KACHE_CACHE_DIR="$RIO_KACHE_CACHE_DIR"
      elif [ -n "''${HOME:-}" ]; then
        export KACHE_CACHE_DIR="$HOME/.cache/rio-build/kache/${kacheEnvSalt}"
      else
        no_store=1
      fi
      if [ "$no_store" = 0 ] && ! kache_disabled; then
        case "$KACHE_CACHE_DIR" in
          # Stamp default epochs AND relocated stores parked under the
          # prune root (a salt-shaped RIO_KACHE_CACHE_DIR would
          # otherwise look idle to the shellHook prune and be rm -rf'd
          # mid-use). Failures never break a compile.
          "''${HOME:-/nonexistent}/.cache/rio-build/kache/"*)
            { mkdir -p "$KACHE_CACHE_DIR" && touch "$KACHE_CACHE_DIR/.last-used"; } 2>/dev/null || true
            ;;
          *) ;;
        esac
      fi

      # Job 5: ONE argv scan classifies the invocation and captures
      # the sweep coordinates (--crate-name is already underscore-form
      # from cargo).
      zflag=0 crate_name="" out_dir="" prev=""
      for a in "$@"; do
        case "$prev" in
          --crate-name) crate_name="$a" ;;
          --out-dir) out_dir="$a" ;;
        esac
        case "$a" in
          -Z* | --unpretty*) zflag=1 ;;
          --crate-name=*) crate_name="''${a#--crate-name=}" ;;
          --out-dir=*) out_dir="''${a#--out-dir=}" ;;
        esac
        prev="$a"
      done

      # Bypassed compiles sweep their own debris first: kache
      # pre-cleans restored outputs before its own real compiles, but a
      # bypass runs plain rustc, which EACCESes on read-only restores
      # (or, under uid 0, silently truncates a SHARED store inode).
      # Restores come in three shapes (kache v0.4.0):
      #  - hardlink: nlink >= 2, mode 0444, inode SHARED with the
      #    store blob (LinkStrategy::Hardlink fallback, link.rs:81);
      #  - reflink: nlink = 1, mode 0444 — link_to_target tries
      #    reflink FIRST (link.rs:52) and set_executable_perms is
      #    Copy-strategy-only (link.rs:53-57, :103-108), so
      #    .rlib/.rmeta/.o/.d restores on a reflink fs keep the blob's
      #    read-only mode at nlink 1;
      #  - post-eviction debris: unlink_blob (store.rs:40-50, reached
      #    via remove_entry :1007-1012) chmods the shared inode
      #    writable best-effort, then unlinks the store name — the
      #    surviving target file is usually nlink-1 0666 (benign:
      #    plain rustc overwrites it), but nlink-1 0444 when that
      #    chmod failed.
      # Crate-name arm: the predicate is read-only ALONE — at
      # -maxdepth 1 of this compile's --out-dir, an ANCHORED
      # {lib,}<crate>-* match is either a rustc output (created
      # writable) or a kache restore, so a -links +1 narrowing would
      # just resurrect the EACCES for the nlink-1 shapes above. The
      # anchor matters too: an unanchored *<crate>* would let crate
      # foo's sweep unlink a just-restored libfoo_bar-* sibling output
      # mid-parallel-build. A read-only file a user manually parked at
      # depth 1 of a cargo --out-dir under exactly that name pattern
      # is accepted collateral (the dir is cargo-owned). The fallback
      # arm (no --crate-name: non-cargo spawners only — cargo always
      # passes it) keeps the conservative shared-inode signature
      # `-links +1`, since without a name anchor read-only alone could
      # hit user files in a hand-rolled --out-dir.
      # `! -perm -u+w` is a mode-bit test, not access(2) `-writable`:
      # the latter is vacuous under uid 0, and root skipping the
      # unlink means rustc's truncating open rewrites the shared store
      # inode. Executables/dylibs need no sweep: LinkStrategy::Copy
      # (compiler/mod.rs:200-205) restores them 0755 nlink-1, which
      # the predicate skips. Never chmod: the nlink >= 2 shape still
      # shares the store inode — chmod + overwrite would poison every
      # future restore of that blob.
      sweep_debris() {
        [ -n "$out_dir" ] && [ -d "$out_dir" ] || return 0
        if [ -n "$crate_name" ]; then
          find "$out_dir" -maxdepth 1 -type f \
            \( -name "lib''${crate_name}-*" -o -name "''${crate_name}-*" \) \
            ! -perm -u+w -delete 2>/dev/null || true
        else
          find "$out_dir" -maxdepth 1 -type f \
            -links +1 ! -perm -u+w -delete 2>/dev/null || true
        fi
      }

      # Job 6: routing. run_real is the single plain-compiler
      # chokepoint — every bypass sweeps, then execs the real thing;
      # kache never runs on these paths.
      run_real() {
        sweep_debris
        exec "$@"
      }
      # Disabled bypass: kache's disabled mode is pure passthrough (no
      # lookup, no store, no pre-clean), so without this arm a
      # disabled rebuild EACCESes on restores from earlier enabled
      # runs — the exact hole xtask's regen-sqlx tree-wide pre-clean
      # was built around (xtask/src/regen/sqlx.rs). CLI words fall
      # through with KACHE_DISABLED intact — kache sees the flag.
      if kache_disabled && is_compiler "''${1:-}"; then
        run_real "$@"
      fi
      # -Z bypass (header job 6 has the full rationale + watch item).
      if [ "$zflag" = 1 ] && is_compiler "''${1:-}"; then
        run_real "$@"
      fi
      # Online-mode sqlx bypass (header job 6 has the full rationale).
      # The is_compiler gate keeps CLI invocations (kache stats) out
      # of the bypass — and it must be the fixed allowlist above,
      # because kache's own subcommand words `init` and `sync` DO
      # resolve to PATH binaries here.
      if ! sqlx_offline_truthy && [ -n "''${DATABASE_URL:-}" ] && is_compiler "''${1:-}"; then
        run_real "$@"
      fi
      if [ "$no_store" = 1 ]; then
        # No HOME, no override: nowhere sane for a store. Bypass to
        # the real compiler when argv[1] is one; CLI usage falls
        # through disabled.
        if is_compiler "''${1:-}"; then
          run_real "$@"
        fi
        export KACHE_DISABLED=1
      fi
      exec ${kachePkg}/bin/kache "$@"
    '';
  };

  shellPackages = with pkgs; [
    # CI gate driver — `nix-fast-build --flake .#checks.x86_64-linux`
    # streams eval+build (per-attr nix-eval-jobs workers → builds
    # queue as drvs become known). Replaces the old `.#ci` aggregate.
    nix-fast-build

    # Cargo tools
    cargo-edit
    cargo-expand
    cargo-fuzz # works in default (nightly) shell; errors on stable
    cargo-hakari # workspace-hack regen — `cargo xtask regen hakari`
    cargo-mutants # dev-only mutation testing — see `cargo xtask mutants` / `.#mutants`
    cargo-nextest
    cargo-outdated
    cargo-watch

    # Cross-worktree cargo build cache — the policy-wrapped RUSTC_WRAPPER
    # (a static shell env attr), doubling as the CLI: `kache stats`,
    # `kache why-miss <crate>`, `kache purge --crate-name <crate>`,
    # `kache gc`, `kache doctor`. The wrapper means CLI invocations see
    # the same pinned config + store as wrapped compiles.
    kacheWrapped

    # Debugging tools
    lldb
    gdb
    lcov # `lcov --summary`/`--list` on the coverage output
    stress-ng # flake-repro under load (.claude/rules/ci-failure-patterns.md)

    # Documentation
    # Typst design book — wrapped typst (with @preview/* closure
    # baked in via TYPST_PACKAGE_CACHE_PATH), shiroa HTML generator,
    # and the typstyle formatter (wired into treefmt). typstEnv below
    # exports the same TYPST_* vars for shiroa's in-process resolver.
    docsLib.rioTypst
    # shiroa's embedded reflexo-typst ignores TYPST_PACKAGE_CACHE_PATH —
    # it resolves @preview/* via $XDG_DATA_HOME/typst/packages and WRITES
    # its bundled @preview/shiroa there on startup, so it needs a writable
    # copy of the rioTypst package closure. Wrap to sync the closure into
    # docs/.cache/typst-xdg/ (gitignored) on first run and whenever
    # rioTypst changes, then exec the real shiroa with XDG_DATA_HOME
    # pointed there. The sentinel file holds the source store path so a
    # `direnv reload` after a typstDeps change re-syncs.
    (writeShellScriptBin "shiroa" ''
      set -euo pipefail
      src="${docsLib.rioTypst}/lib/typst/packages"
      cache="''${RIO_TYPST_XDG:-$PWD/docs/.cache/typst-xdg}"
      sentinel="$cache/.rio-typst-src"
      if [[ ! -f "$sentinel" || "$(cat "$sentinel")" != "$src" ]]; then
        echo "shiroa: syncing typst package closure → $cache" >&2
        rm -rf "$cache"
        mkdir -p "$cache/typst"
        cp -rL "$src" "$cache/typst/packages"
        chmod -R u+w "$cache/typst"
        echo "$src" > "$sentinel"
      fi
      export XDG_DATA_HOME="$cache"
      # No stderr filtering — piping through grep would strip ANSI colour
      # (shiroa's logger checks isatty). The per-chapter "html export is
      # under active development" banner is tolerable noise in exchange.
      #
      # NOTE: `shiroa serve` output is NOT post-processed. The nix build
      # (`.#docs`) runs nix/docs-svg-dedup.py (glyph-sprite hoist,
      # dyn-render JS strip) and derives 404.html from intro.html.
      # Under `serve` you'll see: sla-sizing.html
      # ~10.5MB (vs ~4.4MB built); 404.html missing; refs.gh() links
      # carry `gh-sha=dirty`. All cosmetic — `nix build .#docs` is the
      # canonical output.
      exec ${shiroaPkg}/bin/shiroa "$@"
    '')
    typstyle

    # Integration test deps
    postgresql_18
    sqlxCli # `cargo xtask regen sqlx` + `cargo sqlx migrate` (0.9 pin, see above)

    # Local dev stack (`process-compose up`)
    process-compose

    # Formatting (nix fmt also works, but direct treefmt is handy)
    treefmtWrapper

    # Spec-coverage: `tracey query validate`, `tracey web`
    traceyPkg

    # crate2nix CLI for regenerating Cargo.json after
    # Cargo.lock changes. PoC — see
    # .claude/notes/crate2nix-migration-assessment.md.
    crate2nixCli

    # Dashboard dev: `pnpm install --lockfile-only` (hash bumps),
    # `pnpm run dev` (vite dev server with Envoy proxy). Proto
    # stubs regen: `cd rio-dashboard && buf generate --template
    # buf.gen.yaml ../rio-proto/proto` (src/gen/ is gitignored).
    nodejs
    pnpm_10
    buf
    protoc-gen-es

    # Deploy tooling for infra/eks/. Large closures (awscli2
    # pulls python3 + botocore) but the user asked for
    # everything-in-one-shell over a separate .#deploy.
    # Scripts under infra/eks/ also carry nix-shell shebangs
    # pointing at these same packages, so they work even if
    # someone runs them outside `nix develop`.
    awscli2
    coldsnap # cargo xtask k8s -p eks ami push — direct-to-EBS-snapshot upload (ADR-021)
    ssm-session-manager-plugin # cargo xtask k8s -p eks smoke — SSM tunnel to NLB
    lsof # cargo xtask k8s rsb — reap stale tunnel listeners on :2222
    # opentofu (not terraform: BSL license → unfree in nixpkgs)
    # with providers bundled via withPlugins. No `tofu init`
    # download step — providers are in the nix store, pinned by
    # nixpkgs rev. .terraform.lock.hcl is gitignored (nix is the
    # lock). The provider set must cover transitive module deps
    # too (EKS module pulls cloudinit + null).
    (opentofu.withPlugins (p: [
      p.hashicorp_aws
      p.hashicorp_helm
      p.hashicorp_kubernetes
      p.hashicorp_random
      p.hashicorp_tls
      p.hashicorp_time
      p.hashicorp_cloudinit # transitive: terraform-aws-modules/eks
      p.hashicorp_null # transitive: terraform-aws-modules/eks
      p.hashicorp_http # addons.tf: fetch Gateway API CRD yaml
      p.gavinbunney_kubectl # addons.tf: apply Gateway API CRDs (kubernetes_manifest can't — plan-time API validation)
    ]))
    kubectl
    skopeo # cargo xtask k8s push -p eks — docker-archive → ECR
    manifest-tool # cargo xtask k8s push -p eks — multi-arch OCI index
    kubernetes-helm
    cilium-cli # cilium status, cilium hubble ui (port-forward)
    hubble # hubble observe --server localhost:4245 (after port-forward to hubble-relay)
    kubeconform # ad-hoc schema validation (no pre-commit hook — fetches 300MB, sandbox blocks)
    yq-go # nix/helm-render.nix
    grpcurl # manual AdminService poking when rio-cli isn't enough
    openssl # openssl rand 32 → HMAC key
    git
  ];

  # Shared mkShell builder. Lists build deps explicitly
  # (openssl, libclang, sys-crate libs for pkg-config
  # probes, protobuf+cmake for rio-proto's codegen).
  mkRioShell =
    rust:
    (pkgs.mkShell.override {
      # mold via cc-wrapper: rustc's linker is `cc`, so this
      # speeds dev-loop relinks without touching RUSTFLAGS
      # (target-dir fingerprints stay valid). crate2nix
      # uses its own stdenv — `nix build` stays on GNU ld.
      stdenv = moldStdenv;
    })
      (
        sysCrateEnv.allEnv
        // docsLib.typstEnv
        // {
          packages = [ rust ] ++ shellPackages;
          nativeBuildInputs = with pkgs; [
            pkg-config
            protobuf
            cmake
          ];
          buildInputs =
            with pkgs;
            [
              openssl
              llvmPackages.libclang.lib
            ]
            ++ sysCrateEnv.allLibs;
          RUST_BACKTRACE = "1";
          PROTOC = "${pkgs.protobuf}/bin/protoc";
          LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
          PG_BIN = "${pkgs.postgresql_18}/bin";
          # sqlx query! macros read .sqlx/ instead of connecting
          # to PG. `cargo build` works without a live DB.
          # `cargo xtask regen sqlx` unsets this locally to regenerate.
          SQLX_OFFLINE = "true";
          RUST_SRC_PATH = "${rust}/lib/rustlib/src/rust/library";
          # Purpose-built "inside the rio dev shell" sentinel. Hooks and
          # scripts that need to know (sqlx-prepare-check) test THIS, not
          # generic tool vars like PROTOC that any protobuf project's
          # shell also exports.
          RIO_DEVSHELL = "1";
          # Cross-worktree cargo build cache (github:kunobi-ninja/kache).
          # Content-addressed RUSTC_WRAPPER: blake3 keys are path-
          # normalized (workspace root → sentinel), so byte-identical
          # sources in sibling worktrees share one artifact store. All
          # policy lives in kacheWrapped + kacheConfig above; the value
          # here is the wrapper's own store path — per-shell and
          # immutable, so each environment atomically carries the
          # salt+config it was evaluated with, and sibling worktrees on
          # different revs cannot cross-contaminate store epochs (any
          # shared mutable indirection — a state-dir symlink, say — is
          # last-writer-wins across concurrent shells). Empirically,
          # current cargo does NOT hash the RUSTC_WRAPPER value into
          # unit fingerprints (verified: toggling it on a warm target →
          # zero recompiles), so per-rev paths cost nothing; if a future
          # cargo starts hashing it, the cost is one rebuild per rev
          # hop, never a correctness issue. Devshell-only, same contract
          # as the mold override: crate2nix builds run in the hermetic
          # sandbox and never see this env.
          RUSTC_WRAPPER = "${kacheWrapped}/bin/kache";
          #
          # Verified against kache v0.4.0 source (cache_key.rs, args.rs,
          # link.rs, wrapper.rs):
          #  - fail-open: cache/store errors fall back to real rustc, so
          #    the pre-commit sqlx-prepare-check leak path cannot block
          #    commits (it also skips outside the shell and when
          #    RUSTC_WRAPPER no longer resolves after a store gc — see
          #    nix/pre-commit-hooks.nix);
          #  - KACHE_DISABLED=1 toggles caching with zero rebuild cost
          #    (and works on any cargo, fingerprinting or not);
          #  - hits replay the original compile's stderr verbatim, so
          #    cargo's warning replay keeps working;
          #  - incremental: kache strips -C incremental from wrapped
          #    builds; both main-workspace profiles already set
          #    incremental=false, so nothing changes there;
          #  - toolchains: the full `rustc -vV` text is in the key, so
          #    nightly/stable/clippy never collide — but clippy LINT
          #    FLAGS are not keyed (neither argv -W/-D nor CLIPPY_ARGS):
          #    changing flags on a warm cache can replay a stale verdict.
          #    The merge gate is the hermetic /nixbuild --checks; use
          #    KACHE_DISABLED=1 for one-off lint-flag experiments;
          #  - env!-baked absolute paths (xtask's repo_root via
          #    CARGO_MANIFEST_DIR, CARGO_BIN_EXE_* in test harnesses) are
          #    keyed RAW by upstream design → those binaries are
          #    per-worktree: never shared, never wrong;
          #  - cached compiles carry --remap-path-prefix sentinels, so
          #    debuginfo paths read <WORKSPACE>/… — see CLAUDE.md for the
          #    gdb/lldb substitute-path recipe;
          #  - devshell `cargo fuzz` TARGET-unit compiles carry
          #    -Zsanitizer on argv (cargo-fuzz routes it via RUSTFLAGS,
          #    which only reach target units) and take the wrapper's -Z
          #    passthrough: uncached, incremental preserved. Fuzz HOST
          #    units — build scripts, proc-macros, their dep rlibs —
          #    carry no -Z token and ARE cached normally through kache,
          #    with -C incremental stripped (CI fuzz derivations are
          #    hermetic and unaffected either way).
          #
          # Repo-local kubeconfig: xtask k8s writes here, so
          # direct kubectl/helm in the shell hits the same
          # cluster. Matches xtask/src/sh.rs:kubeconfig_path().
          shellHook = ''
            export KUBECONFIG="$PWD/.kube/config"
            # Anchor the shiroa wrapper's XDG cache to repo-root regardless
            # of invocation cwd (bug_022: `cd docs && shiroa serve .`
            # otherwise writes to docs/docs/.cache/). git rev-parse so
            # `nix develop` from a subdirectory also resolves correctly.
            export RIO_TYPST_XDG="$(git rev-parse --show-toplevel)/docs/.cache/typst-xdg"
            # kache wiring. Policy (local-only allowlist, pinned config,
            # salted store) lives in the kacheWrapped script — two
            # shell-side jobs remain, plus the sqlx contract export
            # (all three need the worktree root).
            rio_root="$(git rev-parse --show-toplevel)"
            # Single-channel sqlx contract: this is the one variable both
            # sqlx-macros-core (first in its own discovery chain) and
            # rio-buildhash's RIO_SQLX_HASH tracker read, so the offline
            # cache the macros expand against and the one the cache key
            # hashes are the same directory by construction. Exported
            # whenever rio_root IS a rio checkout (same uniquely-rio
            # marker as the knob loader below): a foreign-repo
            # invocation must not export the foreign root's .sqlx — if
            # that dir EXISTS, rio compiles started elsewhere would
            # Track-hash the wrong cache while sqlx's per-query lookup
            # falls through to the real workspace .sqlx (a kache key
            # that never observed its input); if it doesn't exist, the
            # tracker goes unkeyed (per-run-unique RIO_SQLX_HASH,
            # rio-buildhash/src/lib.rs unkeyed() — never replayable,
            # just permanent misses). Left unset instead, the tracker's
            # `untracked` warning makes the state loud without steering
            # a foreign project's own macros. The
            # export overrides any inherited value on purpose (a stale
            # sibling-worktree value would retarget both readers); a
            # per-invocation override (SQLX_OFFLINE_DIR=… cargo check)
            # still works for debugging after shell entry.
            if [ -f "$rio_root/rio-buildhash/Cargo.toml" ]; then
              export SQLX_OFFLINE_DIR="$rio_root/.sqlx"
            else
              # Foreign-checkout entry: a stale inherited value (sibling
              # worktree shell, IDE-captured env) must not survive — both
              # readers would silently use the WRONG worktree's cache and
              # the tracker would take the Track arm, so the loud
              # degraded path would never fire. Unset restores it.
              unset SQLX_OFFLINE_DIR
            fi
            # (a) Honor the supported per-user knobs from .env.local even
            #     without direnv (`nix develop -c …` from a bare shell).
            #     Already-exported values win (direnv loads .env.local
            #     before the flake). Plain values only — direnv and
            #     xtask's dotenvy parse quotes/escapes, a raw shell
            #     export would not, so anything outside [A-Za-z0-9_/.+-]
            #     is rejected with a warning rather than letting three
            #     readers disagree. Skipped when the invoker's git
            #     toplevel is not a rio-build checkout (`nix develop
            #     /path/to/rio` from inside a foreign repo must not
            #     import that repo's knobs) — the marker is a
            #     uniquely-rio path, not a generic flake-layout file
            #     another repo would also have.
            if [ -f "$rio_root/rio-buildhash/Cargo.toml" ] && [ -f "$rio_root/.env.local" ]; then
              for kache_knob in KACHE_DISABLED RIO_KACHE_MAX_SIZE RIO_KACHE_CACHE_DIR; do
                if [ -z "''${!kache_knob+x}" ]; then
                  kache_val="$(grep -E "^''${kache_knob}=" "$rio_root/.env.local" | tail -n1 | cut -d= -f2-)" || true
                  if [ -n "$kache_val" ]; then
                    case "$kache_val" in
                      *[!A-Za-z0-9_/.+-]*)
                        echo "devshell: ignoring $kache_knob from .env.local — plain unquoted values only (see .env.local.example)" >&2
                        ;;
                      *) export "$kache_knob=$kache_val" ;;
                    esac
                  fi
                fi
              done
              if grep -qE '^(KACHE_CACHE_DIR|KACHE_MAX_SIZE)=' "$rio_root/.env.local"; then
                echo "devshell: KACHE_CACHE_DIR/KACHE_MAX_SIZE in .env.local are no longer honored (foreign kache configs must not steer our store) — rename to RIO_KACHE_CACHE_DIR/RIO_KACHE_MAX_SIZE" >&2
              fi
              unset kache_knob kache_val
            fi
            # (b) Default-store epoch hygiene: seed this salt's stamp
            #     (the wrapper refreshes it on every invocation — see
            #     job 4 in kacheWrapped) and prune sibling epochs whose
            #     stamp is 14+ days old. Scope and safety rules:
            #     - seeding/re-stamping honors KACHE_DISABLED with
            #       kache's own truthiness ("1" or any-case "true",
            #       v0.4.0 config.rs:149-151), mirroring the wrapper's
            #       stamp gate: an opted-out user's dead store must age
            #       out, not be re-seeded at every shell entry. The
            #       knob loader above runs first, so a .env.local
            #       opt-out is honored here too;
            #     - a configured RIO_KACHE_CACHE_DIR parked UNDER this
            #       root is re-stamped before the prune (mirror of
            #       wrapper job 4): it may be 12-hex salt-shaped, and
            #       without a fresh stamp a 14-day-idle relocated store
            #       would be rm -rf'd at shell entry before the first
            #       compile could re-stamp it;
            #     - only 12-hex salt-shaped dirnames are pruned: a
            #       .last-used stamp records "a wrapper/shell
            #       invocation resolved to this store", not "kache
            #       read or wrote it" — nothing stamps a parked dir
            #       once it stops being configured, so the name-shape
            #       gate is the structural guard that keeps human-named
            #       dirs out of the reaper;
            #     - a salt-shaped dir missing its stamp is stamped now,
            #       never deleted (a recreated epoch cannot become
            #       invisible to this GC);
            #     - the prune runs even when RIO_KACHE_CACHE_DIR is set
            #       or caching is disabled (only seeding/re-stamping is
            #       skipped) so relocated and opted-out users still age
            #       out their stale epochs instead of leaking 256GiB
            #       dirs forever;
            #     - every command is failure-guarded: a read-only HOME
            #       or a racing sibling prune must not abort direnv's
            #       strict-mode env load.
            #     NUL-delimited (paths under $HOME may contain spaces);
            #     GNU find -regex/-printf: Linux-only, harmless no-op
            #     elsewhere.
            rio_kache_root="$HOME/.cache/rio-build/kache"
            rio_kache_kd="''${KACHE_DISABLED:-}"
            if [ "$rio_kache_kd" != "1" ] && [ "''${rio_kache_kd,,}" != "true" ]; then
              if [ -z "''${RIO_KACHE_CACHE_DIR:-}" ]; then
                { mkdir -p "$rio_kache_root/${kacheEnvSalt}" \
                  && touch "$rio_kache_root/${kacheEnvSalt}/.last-used"; } 2>/dev/null || true
              else
                case "$RIO_KACHE_CACHE_DIR" in
                  "$rio_kache_root"/*)
                    { mkdir -p "$RIO_KACHE_CACHE_DIR" \
                      && touch "$RIO_KACHE_CACHE_DIR/.last-used"; } 2>/dev/null || true
                    ;;
                  *) ;;
                esac
              fi
            fi
            if [ -d "$rio_kache_root" ]; then
              for rio_epoch in "$rio_kache_root"/*/; do
                rio_epoch_name="$(basename "$rio_epoch")"
                case "$rio_epoch_name" in
                  *[!0-9a-f]*) continue ;;
                esac
                [ "''${#rio_epoch_name}" -eq 12 ] || continue
                [ -e "$rio_epoch.last-used" ] || touch "$rio_epoch.last-used" 2>/dev/null || true
              done
              find "$rio_kache_root" -mindepth 2 -maxdepth 2 -name .last-used \
                -regextype posix-extended -regex '.*/[0-9a-f]{12}/\.last-used' \
                -mtime +14 -printf '%h\0' 2>/dev/null | xargs -0 -r rm -rf -- || true
            fi
            unset rio_epoch rio_epoch_name rio_kache_root rio_kache_kd
            ${preCommitInstall}
          '';
        }
      );
in
{
  default = mkRioShell rustNightly;
  stable = mkRioShell rustStable;
}
