# Dev shells.
#
# Default = nightly so `cargo fuzz run` works out of the box. CI builds
# use stable (rustStable via crate2nix), so if you write nightly-only
# code, checks.clippy-* / checks.nextest-* will catch it.
#
# Use `nix develop .#stable` for strict CI-parity dev.
{
  pkgs,
  rustStable,
  rustNightly,
  sysCrateEnv,
  traceyPkg,
  crate2nixCli,
  # nix/docs.nix — rioTypst (wrapped typst) + typstEnv (TYPST_* vars)
  docsLib,
  shiroaPkg,
  # config.treefmt.build.wrapper — `treefmt` in PATH
  treefmtWrapper,
  # config.pre-commit.installationScript — installs git hooks on shell entry
  preCommitInstall,
  # github:kunobi-ninja/kache — cross-worktree RUSTC_WRAPPER build cache.
  # Consumed via kacheWrapped (policy wrapper: local-only allowlist,
  # pinned config, env-salted store) — never used bare. See kacheWrapped.
  kachePkg,
}:
let
  # nixpkgs still ships sqlx-cli 0.8.6 while the workspace is on sqlx
  # 0.9. `cargo sqlx prepare` must match the library major (it drives
  # the .sqlx/ query cache that sqlx-macros 0.9 consumes, and 0.9
  # changed nullability inference), so pin 0.9.0 here. Feature set
  # mirrors the nixpkgs expression. Drop this override — and the
  # reference below — once nixpkgs ships sqlx-cli ≥ 0.9.
  sqlxCli =
    let
      version = "0.9.0";
      src = pkgs.fetchCrate {
        pname = "sqlx-cli";
        inherit version;
        hash = "sha256-XariusjsCgn0Qai0XWtr7EzSzDDTp1cCzjff1kJNO9Y=";
      };
    in
    pkgs.sqlx-cli.overrideAttrs (_old: {
      inherit version src;
      cargoDeps = pkgs.rustPlatform.fetchCargoVendor {
        inherit src;
        name = "sqlx-cli-${version}-vendor";
        hash = "sha256-pHaMKuB9v3fjbgeVyLyRtfoQ9BkE6z+TjDfdBaVdbXM=";
      };
    });

  # mold-linking stdenv for the dev shells (see the mkShell.override note
  # below). Bound here because kache's store-epoch salt hashes its cc: the
  # cc-wrapper store path moves whenever gcc, mold, bintools, or glibc
  # change — exactly the link inputs kache's cache key cannot see.
  moldStdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.stdenv;

  # kache config, force-pinned via KACHE_CONFIG inside the kacheWrapped
  # script below (the env var short-circuits kache's config search, so a
  # user-level ~/.config/kache/config.toml — possibly holding S3 creds for
  # other projects — can never load here). Two values; everything else
  # matters by ABSENCE: no [cache.remote] and no [cache.planner] sections
  # means kache has nothing to talk to but the local store, and the
  # wrapper's allowlist drops any remote env vars before they could
  # override this file. Per-user knobs: KACHE_DISABLED=1 / KACHE_MAX_SIZE /
  # KACHE_CACHE_DIR in .env.local (see .env.local.example).
  kacheConfig = pkgs.writeText "kache-config.toml" ''
    # Generated by rio-build's nix/devshell.nix. Local-only on purpose:
    # no [cache.remote], no [cache.planner]. Per-user tuning goes in
    # .env.local — env vars override this file.
    [cache]
    # kache's 50GiB default is sized for one checkout; ~20 sibling
    # worktrees x two toolchains need room. The local store is
    # content-addressed raw blobs, refcount-deduped (zstd applies to
    # remote packs only — verified v0.4.0 src/store.rs).
    local_max_size = "256GiB"
    # Also cache bin crates + nextest harness binaries (kache skips
    # "user-facing executables" by default). This workspace links five
    # fat service bins + 51 test binaries — the critical path of a full
    # build in a fresh worktree is exactly those links, so without this
    # the dep cache halves CPU but barely moves wall-clock. Executables
    # restore by reflink-or-copy (never hardlink, v0.4.0 src/link.rs),
    # and the store epoch is salted by the link environment (see
    # kacheEnvSalt) so a restored binary's PT_INTERP/RPATH always exists.
    cache_executables = true
  '';

  # Salt for the kache store location. kache's key for linked artifacts
  # sees the linker only as the first line of `cc --version` (verified
  # v0.4.0 src/cache_key.rs:1186-1211) — glibc, crt objects, mold, and
  # the cc-wrapper store path are all invisible. After a nixpkgs bump +
  # `nix store gc`, an unsalted store would keep restoring executables /
  # dylibs / proc-macros whose ELF interpreter and RPATH point at GC'd
  # store paths: exec fails with a cryptic ENOENT that `cargo clean`
  # cannot fix (the restore repeats). Hashing the mold-stdenv cc path
  # into the store location makes that impossible by construction — the
  # cc-wrapper derivation rehashes whenever any link input changes, so a
  # toolchain bump is a cold cache, never a dangling interpreter. Old
  # epochs are pruned by the shellHook after 14 days unused.
  kacheEnvSalt = builtins.substring 0 12 (builtins.hashString "sha256" (toString moldStdenv.cc));

  # Policy wrapper around kache. The policy must live IN THE BINARY:
  # env hygiene done in the shellHook does not survive everything that
  # re-loads user config into a child environment (xtask's dotenvy
  # re-reads .env.local wholesale; IDEs spawn cargo with their own env).
  # Four jobs:
  #
  #  1. Local-only by ALLOWLIST: every KACHE_* var not explicitly allowed
  #     is dropped, so S3/planner/manifest knobs can never reach kache no
  #     matter who spawned it — and a future kache release that grows new
  #     remote vars is denied by default instead of silently honored.
  #     (KACHE_ACTIVE/KACHE_VERSION pass through: internal coordination
  #     for nested-wrapper detection.) KACHE_CACHE_DIR is deliberately
  #     NOT allowlisted: it is kache's own standard variable, so a
  #     machine-global export from another kache-using project would
  #     silently repoint OUR store — foreign eviction budget, foreign
  #     (possibly remote-fetched) artifacts. The store-relocation knob
  #     is the rio-namespaced RIO_KACHE_CACHE_DIR, which only rio-aware
  #     contexts set.
  #  2. Pin KACHE_CONFIG and the store location: RIO_KACHE_CACHE_DIR if
  #     set, else the repo-scoped, environment-salted epoch (see
  #     kacheEnvSalt) — our 256GiB budget and provenance stay ours
  #     alone. No HOME (some spawners scrub it) → fail OPEN: bypass to
  #     the real compiler instead of aborting under nounset.
  #  3. Never cache what kache cannot key: v0.4.0 has no -Z parse arm
  #     at all (src/args.rs — unknown argv tokens fall through), so ANY
  #     -Z flag on the rustc command line is invisible to the cache key.
  #     -Z flags travelling via RUSTFLAGS are keyed (kache hashes
  #     CARGO_ENCODED_RUSTFLAGS) — but cargo also splices RUSTFLAGS onto
  #     argv, and the wrapper cannot tell which route a token took, so
  #     the safe invariant is: any -Z token → passthrough, uncached.
  #     This subsumes the original -Zunpretty case (cargo expand on a
  #     warm cache would "hit" the ordinary compile's entry and emit
  #     nothing) and means devshell `cargo fuzz` builds (-Zsanitizer)
  #     run uncached — a deliberate trade of fuzz-dep caching for
  #     immunity to unkeyed-flag collisions.
  #  4. Stamp the default store epoch's .last-used on every invocation:
  #     the shellHook prune decides "abandoned" from this stamp, and
  #     long-lived sessions (tmux panes, IDE-captured envs) compile for
  #     weeks without re-entering a shell — liveness must ride the
  #     compile, not the shell entry.
  kacheWrapped = pkgs.writeShellApplication {
    name = "kache";
    text = ''
      # Any -Z token (joined or two-arg form: a bare "-Z" matches too)
      # → run the real compiler uncached. See policy job 3.
      for a in "$@"; do
        case "$a" in
          -Z* | --unpretty*) exec "$@" ;;
          *) ;;
        esac
      done
      allow=" KACHE_ACTIVE KACHE_VERSION KACHE_CACHE_EXECUTABLES \
        KACHE_CLEAN_INCREMENTAL KACHE_COMPRESSION_LEVEL KACHE_DAEMON_IDLE_TIMEOUT \
        KACHE_DISABLED KACHE_LOG KACHE_LOG_FILE KACHE_LOG_FILE_PATH KACHE_MAX_SIZE \
        KACHE_PROGRESS "
      # Pure-bash prefix expansion — no externals, nothing that can fail
      # silently inside a process substitution.
      for name in "''${!KACHE_@}"; do
        case "$allow" in
          *" $name "*) ;;
          *) unset "$name" ;;
        esac
      done
      export KACHE_CONFIG=${kacheConfig}
      if [ -n "''${RIO_KACHE_CACHE_DIR:-}" ]; then
        export KACHE_CACHE_DIR="$RIO_KACHE_CACHE_DIR"
      elif [ -n "''${HOME:-}" ]; then
        export KACHE_CACHE_DIR="$HOME/.cache/rio-build/kache/${kacheEnvSalt}"
        # Liveness stamp for the shellHook's epoch prune. Failures must
        # never break a compile (read-only HOME, racing a prune) — the
        # store itself fails open inside kache too.
        { mkdir -p "$KACHE_CACHE_DIR" && touch "$KACHE_CACHE_DIR/.last-used"; } 2>/dev/null || true
      else
        # No HOME, no override: nowhere sane for a store. In wrapper
        # usage argv[1] is the real compiler — bypass kache entirely
        # rather than abort; CLI usage falls through disabled.
        if [ -x "''${1:-}" ]; then
          exec "$@"
        fi
        export KACHE_DISABLED=1
      fi
      exec ${kachePkg}/bin/kache "$@"
    '';
  };

  shellPackages = with pkgs; [
    # CI gate driver — `nix-fast-build --flake .#checks.x86_64-linux`
    # streams eval+build (per-attr nix-eval-jobs workers → builds
    # queue as drvs become known). Replaces the old `.#ci` aggregate.
    nix-fast-build

    # Cargo tools
    cargo-edit
    cargo-expand
    cargo-fuzz # works in default (nightly) shell; errors on stable
    cargo-hakari # workspace-hack regen — `cargo xtask regen hakari`
    cargo-mutants # dev-only mutation testing — see `cargo xtask mutants` / `.#mutants`
    cargo-nextest
    cargo-outdated
    cargo-watch

    # Cross-worktree cargo build cache — the policy-wrapped RUSTC_WRAPPER
    # (exported by the shellHook), doubling as the CLI: `kache stats`,
    # `kache why-miss <crate>`, `kache purge --crate-name <crate>`,
    # `kache gc`, `kache doctor`. The wrapper means CLI invocations see
    # the same pinned config + store as wrapped compiles.
    kacheWrapped

    # Debugging tools
    lldb
    gdb
    lcov # `lcov --summary`/`--list` on the coverage output
    stress-ng # flake-repro under load (.claude/rules/ci-failure-patterns.md)

    # Documentation
    # Typst design book — wrapped typst (with @preview/* closure
    # baked in via TYPST_PACKAGE_CACHE_PATH), shiroa HTML generator,
    # and the typstyle formatter (wired into treefmt). typstEnv below
    # exports the same TYPST_* vars for shiroa's in-process resolver.
    docsLib.rioTypst
    # shiroa's embedded reflexo-typst ignores TYPST_PACKAGE_CACHE_PATH —
    # it resolves @preview/* via $XDG_DATA_HOME/typst/packages and WRITES
    # its bundled @preview/shiroa there on startup, so it needs a writable
    # copy of the rioTypst package closure. Wrap to sync the closure into
    # docs/.cache/typst-xdg/ (gitignored) on first run and whenever
    # rioTypst changes, then exec the real shiroa with XDG_DATA_HOME
    # pointed there. The sentinel file holds the source store path so a
    # `direnv reload` after a typstDeps change re-syncs.
    (writeShellScriptBin "shiroa" ''
      set -euo pipefail
      src="${docsLib.rioTypst}/lib/typst/packages"
      cache="''${RIO_TYPST_XDG:-$PWD/docs/.cache/typst-xdg}"
      sentinel="$cache/.rio-typst-src"
      if [[ ! -f "$sentinel" || "$(cat "$sentinel")" != "$src" ]]; then
        echo "shiroa: syncing typst package closure → $cache" >&2
        rm -rf "$cache"
        mkdir -p "$cache/typst"
        cp -rL "$src" "$cache/typst/packages"
        chmod -R u+w "$cache/typst"
        echo "$src" > "$sentinel"
      fi
      export XDG_DATA_HOME="$cache"
      # No stderr filtering — piping through grep would strip ANSI colour
      # (shiroa's logger checks isatty). The per-chapter "html export is
      # under active development" banner is tolerable noise in exchange.
      #
      # NOTE: `shiroa serve` output is NOT post-processed. The nix build
      # (`.#docs`) runs nix/docs-svg-dedup.py (glyph-sprite hoist,
      # dyn-render JS strip) and derives 404.html from intro.html.
      # Under `serve` you'll see: sla-sizing.html
      # ~10.5MB (vs ~4.4MB built); 404.html missing; refs.gh() links
      # carry `gh-sha=dirty`. All cosmetic — `nix build .#docs` is the
      # canonical output.
      exec ${shiroaPkg}/bin/shiroa "$@"
    '')
    typstyle

    # Integration test deps
    postgresql_18
    sqlxCli # `cargo xtask regen sqlx` + `cargo sqlx migrate` (0.9 pin, see above)

    # Local dev stack (`process-compose up`)
    process-compose

    # Formatting (nix fmt also works, but direct treefmt is handy)
    treefmtWrapper

    # Spec-coverage: `tracey query validate`, `tracey web`
    traceyPkg

    # crate2nix CLI for regenerating Cargo.json after
    # Cargo.lock changes. PoC — see
    # .claude/notes/crate2nix-migration-assessment.md.
    crate2nixCli

    # Dashboard dev: `pnpm install --lockfile-only` (hash bumps),
    # `pnpm run dev` (vite dev server with Envoy proxy). Proto
    # stubs regen: `cd rio-dashboard && buf generate --template
    # buf.gen.yaml ../rio-proto/proto` (src/gen/ is gitignored).
    nodejs
    pnpm_10
    buf
    protoc-gen-es

    # Deploy tooling for infra/eks/. Large closures (awscli2
    # pulls python3 + botocore) but the user asked for
    # everything-in-one-shell over a separate .#deploy.
    # Scripts under infra/eks/ also carry nix-shell shebangs
    # pointing at these same packages, so they work even if
    # someone runs them outside `nix develop`.
    awscli2
    coldsnap # cargo xtask k8s -p eks ami push — direct-to-EBS-snapshot upload (ADR-021)
    ssm-session-manager-plugin # cargo xtask k8s -p eks smoke — SSM tunnel to NLB
    lsof # cargo xtask k8s rsb — reap stale tunnel listeners on :2222
    # opentofu (not terraform: BSL license → unfree in nixpkgs)
    # with providers bundled via withPlugins. No `tofu init`
    # download step — providers are in the nix store, pinned by
    # nixpkgs rev. .terraform.lock.hcl is gitignored (nix is the
    # lock). The provider set must cover transitive module deps
    # too (EKS module pulls cloudinit + null).
    (opentofu.withPlugins (p: [
      p.hashicorp_aws
      p.hashicorp_helm
      p.hashicorp_kubernetes
      p.hashicorp_random
      p.hashicorp_tls
      p.hashicorp_time
      p.hashicorp_cloudinit # transitive: terraform-aws-modules/eks
      p.hashicorp_null # transitive: terraform-aws-modules/eks
      p.hashicorp_http # addons.tf: fetch Gateway API CRD yaml
      p.gavinbunney_kubectl # addons.tf: apply Gateway API CRDs (kubernetes_manifest can't — plan-time API validation)
    ]))
    kubectl
    skopeo # cargo xtask k8s push -p eks — docker-archive → ECR
    manifest-tool # cargo xtask k8s push -p eks — multi-arch OCI index
    kubernetes-helm
    cilium-cli # cilium status, cilium hubble ui (port-forward)
    hubble # hubble observe --server localhost:4245 (after port-forward to hubble-relay)
    kubeconform # ad-hoc schema validation (no pre-commit hook — fetches 300MB, sandbox blocks)
    yq-go # nix/helm-render.nix
    grpcurl # manual AdminService poking when rio-cli isn't enough
    openssl # openssl rand 32 → HMAC key
    git
  ];

  # Shared mkShell builder. Lists build deps explicitly
  # (openssl, libclang, sys-crate libs for pkg-config
  # probes, protobuf+cmake for rio-proto's codegen).
  mkRioShell =
    rust:
    (pkgs.mkShell.override {
      # mold via cc-wrapper: rustc's linker is `cc`, so this
      # speeds dev-loop relinks without touching RUSTFLAGS
      # (target-dir fingerprints stay valid). crate2nix
      # uses its own stdenv — `nix build` stays on GNU ld.
      stdenv = moldStdenv;
    })
      (
        sysCrateEnv.allEnv
        // docsLib.typstEnv
        // {
          packages = [ rust ] ++ shellPackages;
          nativeBuildInputs = with pkgs; [
            pkg-config
            protobuf
            cmake
          ];
          buildInputs =
            with pkgs;
            [
              openssl
              llvmPackages.libclang.lib
            ]
            ++ sysCrateEnv.allLibs;
          RUST_BACKTRACE = "1";
          PROTOC = "${pkgs.protobuf}/bin/protoc";
          LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
          PG_BIN = "${pkgs.postgresql_18}/bin";
          # sqlx query! macros read .sqlx/ instead of connecting
          # to PG. `cargo build` works without a live DB.
          # `cargo xtask regen sqlx` unsets this locally to regenerate.
          SQLX_OFFLINE = "true";
          RUST_SRC_PATH = "${rust}/lib/rustlib/src/rust/library";
          # Purpose-built "inside the rio dev shell" sentinel. Hooks and
          # scripts that need to know (sqlx-prepare-check) test THIS, not
          # generic tool vars like PROTOC that any protobuf project's
          # shell also exports.
          RIO_DEVSHELL = "1";
          # Cross-worktree cargo build cache (github:kunobi-ninja/kache).
          # Content-addressed RUSTC_WRAPPER: blake3 keys are path-
          # normalized (workspace root → sentinel), so byte-identical
          # sources in sibling worktrees share one artifact store. All
          # policy lives in kacheWrapped + kacheConfig above; the value
          # here is the wrapper's own store path — per-shell and
          # immutable, so each environment atomically carries the
          # salt+config it was evaluated with, and sibling worktrees on
          # different revs cannot cross-contaminate store epochs (any
          # shared mutable indirection — a state-dir symlink, say — is
          # last-writer-wins across concurrent shells). Empirically,
          # current cargo does NOT hash the RUSTC_WRAPPER value into
          # unit fingerprints (verified: toggling it on a warm target →
          # zero recompiles), so per-rev paths cost nothing; if a future
          # cargo starts hashing it, the cost is one rebuild per rev
          # hop, never a correctness issue. Devshell-only, same contract
          # as the mold override: crate2nix builds run in the hermetic
          # sandbox and never see this env.
          RUSTC_WRAPPER = "${kacheWrapped}/bin/kache";
          #
          # Verified against kache v0.4.0 source (cache_key.rs, args.rs,
          # link.rs, wrapper.rs):
          #  - fail-open: cache/store errors fall back to real rustc, so
          #    the pre-commit sqlx-prepare-check leak path cannot block
          #    commits (it also skips outside the shell and when
          #    RUSTC_WRAPPER no longer resolves after a store gc — see
          #    nix/pre-commit-hooks.nix);
          #  - KACHE_DISABLED=1 toggles caching with zero rebuild cost
          #    (and works on any cargo, fingerprinting or not);
          #  - hits replay the original compile's stderr verbatim, so
          #    cargo's warning replay keeps working;
          #  - incremental: kache strips -C incremental from wrapped
          #    builds; both main-workspace profiles already set
          #    incremental=false (the fuzz/ sub-workspaces DO lose dev
          #    incremental — acceptable for fuzz edit loops);
          #  - toolchains: the full `rustc -vV` text is in the key, so
          #    nightly/stable/clippy never collide — but clippy LINT
          #    FLAGS are not keyed (neither argv -W/-D nor CLIPPY_ARGS):
          #    changing flags on a warm cache can replay a stale verdict.
          #    The merge gate is the hermetic /nixbuild --checks; use
          #    KACHE_DISABLED=1 for one-off lint-flag experiments;
          #  - env!-baked absolute paths (xtask's repo_root via
          #    CARGO_MANIFEST_DIR, CARGO_BIN_EXE_* in test harnesses) are
          #    keyed RAW by upstream design → those binaries are
          #    per-worktree: never shared, never wrong;
          #  - cached compiles carry --remap-path-prefix sentinels, so
          #    debuginfo paths read <WORKSPACE>/… — see CLAUDE.md for the
          #    gdb/lldb substitute-path recipe;
          #  - fuzz sub-workspace builds key their parent-dir path deps
          #    (../../rio-nix) under the <HOME> sentinel, which embeds the
          #    worktree name → fuzz artifacts are per-worktree (correct,
          #    just not shared).
          #
          # Repo-local kubeconfig: xtask k8s writes here, so
          # direct kubectl/helm in the shell hits the same
          # cluster. Matches xtask/src/sh.rs:kubeconfig_path().
          shellHook = ''
            export KUBECONFIG="$PWD/.kube/config"
            # Anchor the shiroa wrapper's XDG cache to repo-root regardless
            # of invocation cwd (bug_022: `cd docs && shiroa serve .`
            # otherwise writes to docs/docs/.cache/). git rev-parse so
            # `nix develop` from a subdirectory also resolves correctly.
            export RIO_TYPST_XDG="$(git rev-parse --show-toplevel)/docs/.cache/typst-xdg"
            # kache wiring. Policy (local-only allowlist, pinned config,
            # salted store) lives in the kacheWrapped script — two
            # shell-side jobs remain, plus the sqlx contract export
            # (all three need the worktree root).
            rio_root="$(git rev-parse --show-toplevel)"
            # Single-channel sqlx contract: this is the one variable both
            # sqlx-macros-core (first in its own discovery chain) and
            # rio-buildhash's RIO_SQLX_HASH tracker read, so the offline
            # cache the macros expand against and the one the cache key
            # hashes are the same directory by construction. Exported
            # whenever rio_root IS a rio checkout (same uniquely-rio
            # marker as the knob loader below): a foreign-repo
            # invocation must not export a bogus path — the macros would
            # fall through their chain to a real .sqlx while the tracker
            # pinned a constant sentinel. Left unset instead, the
            # tracker's `untracked` warning makes the state loud. The
            # export overrides any inherited value on purpose (a stale
            # sibling-worktree value would retarget both readers); a
            # per-invocation override (SQLX_OFFLINE_DIR=… cargo check)
            # still works for debugging after shell entry.
            if [ -f "$rio_root/rio-buildhash/Cargo.toml" ]; then
              export SQLX_OFFLINE_DIR="$rio_root/.sqlx"
            fi
            # (a) Honor the supported per-user knobs from .env.local even
            #     without direnv (`nix develop -c …` from a bare shell).
            #     Already-exported values win (direnv loads .env.local
            #     before the flake). Plain values only — direnv and
            #     xtask's dotenvy parse quotes/escapes, a raw shell
            #     export would not, so anything outside [A-Za-z0-9_/.+-]
            #     is rejected with a warning rather than letting three
            #     readers disagree. Skipped when the invoker's git
            #     toplevel is not a rio-build checkout (`nix develop
            #     /path/to/rio` from inside a foreign repo must not
            #     import that repo's knobs) — the marker is a
            #     uniquely-rio path, not a generic flake-layout file
            #     another repo would also have.
            if [ -f "$rio_root/rio-buildhash/Cargo.toml" ] && [ -f "$rio_root/.env.local" ]; then
              for kache_knob in KACHE_DISABLED KACHE_MAX_SIZE RIO_KACHE_CACHE_DIR; do
                if [ -z "''${!kache_knob+x}" ]; then
                  kache_val="$(grep -E "^''${kache_knob}=" "$rio_root/.env.local" | tail -n1 | cut -d= -f2-)" || true
                  if [ -n "$kache_val" ]; then
                    case "$kache_val" in
                      *[!A-Za-z0-9_/.+-]*)
                        echo "devshell: ignoring $kache_knob from .env.local — plain unquoted values only (see .env.local.example)" >&2
                        ;;
                      *) export "$kache_knob=$kache_val" ;;
                    esac
                  fi
                fi
              done
              if grep -q '^KACHE_CACHE_DIR=' "$rio_root/.env.local"; then
                echo "devshell: KACHE_CACHE_DIR in .env.local is no longer honored (foreign kache configs must not repoint our store) — rename it to RIO_KACHE_CACHE_DIR" >&2
              fi
              unset kache_knob kache_val
            fi
            # (b) Default-store epoch hygiene: seed this salt's stamp
            #     (the wrapper refreshes it on every compile — see job 4
            #     in kacheWrapped) and prune sibling epochs whose stamp
            #     is 14+ days old. A dir missing its stamp is stamped
            #     now, never deleted, so a recreated epoch cannot become
            #     invisible to this GC. Skipped under RIO_KACHE_CACHE_DIR
            #     (that store is user-managed). NUL-delimited: the paths
            #     live under $HOME, which may contain spaces. (GNU find
            #     -printf: Linux-only; harmless no-op elsewhere.)
            if [ -z "''${RIO_KACHE_CACHE_DIR:-}" ]; then
              rio_kache_root="$HOME/.cache/rio-build/kache"
              mkdir -p "$rio_kache_root/${kacheEnvSalt}"
              touch "$rio_kache_root/${kacheEnvSalt}/.last-used"
              for rio_epoch in "$rio_kache_root"/*/; do
                [ -e "$rio_epoch.last-used" ] || touch "$rio_epoch.last-used" 2>/dev/null || true
              done
              find "$rio_kache_root" -mindepth 2 -maxdepth 2 -name .last-used \
                -mtime +14 -printf '%h\0' 2>/dev/null | xargs -0 -r rm -rf -- || true
              unset rio_epoch rio_kache_root
            fi
            ${preCommitInstall}
          '';
        }
      );
in
{
  default = mkRioShell rustNightly;
  stable = mkRioShell rustStable;
}
