#!/usr/bin/env python3
"""quint-policy: the falsify-twin-required corpus lint (P1-P6).

Vehicle (adjudicated, bughunt-2 slot 11): zero quint-SEMANTIC work — no
verify/run/TLC. Wiring facts (kind, invariants/witness, step,
vacuityExempt) come ONLY from the constructor meta manifest emitted at
nix eval; ALL structural facts come ONLY from `quint parse --out` JSON
IR (quint 0.32.0; the in-derivation canary pins the IR shape). Text
scanning is rejected for structural facts: live holds-checks bind
conjunction vals while twins bind leaf names (credit needs IR expansion
+ import-graph resolution); quint precedence makes raw-text assignment
analysis unsound (`x' = a or b` parses `(x' = a) or b`); the QNT000
frame discipline identity-assigns every var in every action, so "is the
var written" text heuristics are zero-yield.

The two non-IR inputs are declared configuration, not structure:
  - module -> file mapping (top-level `module X` header lines);
  - the `// quint-policy-latches:` header directive (P5 domain).

Rules:
  P1 twin-required: every wired holds-invariant (conjunctions expanded
     through the IR to val leaves) has >=1 witness-kind check whose main
     module's PARSED import graph reaches the live module declaring the
     invariant's vars AND whose witness read-set intersects the
     invariant's var read-set — or a vacuityExempt{class,reason} with
     class in {boundsOK, scope-bound, pre-r2-untwinned}. A tautology
     (empty var read-set) can never earn twin credit and is not
     exemptable: restate it over the transition relation.
  P2 no-frozen-copies: a witness/run main module must reach >=1 module
     declared OUTSIDE calibration/ via import/instance edges; it may not
     declare a non-action operator shadowing a declaration of a reached
     live module (the def-flip cheat).
  P3 baseline pairing: witness checks are paired (census) with the live
     holds-check covering the same live module — no new TLC anywhere.
  P4 live-writer: every var in a wired invariant's transitive read-set
     has >=1 NON-identity assignment reachable from the declaring
     module's `step` (fallback: all of its actions when no `step`
     exists — legacy abstract modules; hazard (nn)). Syntactic screen
     only — P4 credit NEVER substitutes for the P1 twin (a semantically
     inert non-identity write passes P4; the twin run is the teeth).
  P5 latch integrity: vars named in a live module's
     `// quint-policy-latches:` directive must pass P4 and must not be
     non-identity-assigned by any calibration-module action (oracles
     live in the shared live module; identity frames are legal).
  P6 hygiene: per-class exemption census printed (the owner burn-down
     artifact); unknown exemption classes / unused exemptions are
     errors.
  P7 no-anonymous-conjunct-leaves (round-6 WO-S8-4, bug_087's class
     close): a holds-wired invariant leaf whose IR body — after
     unwrapping local `val` bindings — is an `and` application with
     >=2 NON-NAME operands is a violation ("split into named val
     leaves"). P1's twin engine expands only all-name conjunctions,
     so an anonymous bundle is ONE leaf: a sibling-killing conjunct
     rides it to twin credit while a definitionally-true conjunct
     ships unfalsifiable (the bug_087 shape — its vacuous coverage
     conjunct hid behind the disjointness conjunct that was the
     sibling invariant's negation). Named leaves fall under P1's
     twin-per-leaf engine, and a definitionally-true NAMED leaf can
     never earn a [violation]-verified twin — the tautology becomes
     unshippable. Grandfather: P7_GRANDFATHER below (GENERATED by
     this pass over the conversion-time corpus, frozen; burn-down
     owned by round-7; new entries require a wave ruling).

  P8 action-binding totality (round-12 WO-S9-9iii, live_061's
     matmodel-gap class): every action a WIRED regime's step alphabet
     applies (applications inside the step declaration that resolve to
     action declarations through the import graph) carries a binding
     comment in the contiguous comment block directly above its
     declaration — `// Mirrors: <repo-file>:<symbol>` (the production
     transition the action abstracts; the file must exist under the
     staged mirrors root and contain the symbol token — unresolvable =
     red) or `// Environment: <justification>` (the world's move, a
     frame, or a plane outside the model's subject). The class this
     kills: a modeled transition with ZERO production writers shipping
     invisible for the system's whole life — materializationJob.qnt's
     obsoleteOnProduced was wired into step and verified for months
     while no production arm produced its post-state (live_061; the
     letter resolved under 'cancelled'). A binding line is the
     load-bearing pointer a reviewer and a conformance author follow;
     an unresolvable pointer is exactly as dead as no pointer.
     Grandfather: P8_GRANDFATHER (module census at the conversion,
     frozen; shrink-only; new modules enforced from birth).

Exit nonzero on any P1/P2/P4/P5/P6/P7/P8 violation. --census-only
prints findings without failing (the phase-0 artifact)."""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

EXEMPT_CLASSES = {"boundsOK", "scope-bound", "pre-r2-untwinned"}

# P8 grandfather allowlist — GENERATED, FROZEN at the round-12 WO-S9-9iii
# conversion (banner rule 1: membership is the module census of
# docs/spec/models/**/*.qnt at the conversion tree minus the founding
# enforced module, never author-typed). Generator:
#   grep -rhE '^\\s*module\\s+\\w+' docs/spec/models --include='*.qnt' \\
#     | sed -E 's/^\\s*module\\s+(\\w+).*/\\1/' | sort -u \\
#     | grep -v '^materializationJob$'
# Shrink-only: annotating a module's step alphabet deletes its row; a
# NEW module (born after the conversion) is enforced from birth — it
# never enters this set. Adding a row requires a wave ruling.
P8_GRANDFATHER: frozenset = frozenset(
    {
        "authz",
        "authzCalib064String",
        "authzCalib122DeadLeg",
        "authzCalib213Phase",
        "authzCalib237ForeignKnob",
        "chunkCollect",
        "chunkCollectBase",
        "chunkCollectContend",
        "chunkCollectCorrupt",
        "chunkCollectCrash",
        "chunkCollectLateMarkGuarded",
        "chunkCollectLateMarkUnguarded",
        "chunkCollectNoTouch",
        "chunkCollectParseSkip",
        "chunkCollectReapEpqOuterOnly",
        "chunkCollectShadowEquivalence",
        "chunkCollectShadowNoExclusion",
        "chunkCollectThresholdOrder",
        "chunkCollectWriterBounded",
        "chunkCollectWriterOverrun",
        "chunkLiveness",
        "chunkLivenessBase",
        "chunkLivenessContend",
        "chunkLivenessCorrupt",
        "chunkLivenessCrash",
        "chunkLivenessThresholdOrder",
        "closureCalibA17Unfenced",
        "closureCalibC3NoReprobe",
        "closureCalibF10RecoveryVouchUnscoped",
        "closureCalibF13UnprobedDispatch",
        "closureCalibF14RecoveryKeepsSubstituting",
        "closureCalibF1SkipStoreRecheck",
        "closureCalibF1StaleProduced",
        "closureCalibF2SeedOnlyWalk",
        "closureCalibF3IndetFailFast",
        "closureCalibF3SubstitutableDemoted",
        "closureCalibF4DemandDrop",
        "closureCalibF4VacuousPrune",
        "closureCalibF5WantedOverwrite",
        "closureCalibF6LatchOutlivesChain",
        "closureCalibF7ClearUnbuiltChildren",
        "closureCalibF8DispatchNoEvidence",
        "closureCalibF9PoisonClearNoStamp",
        "closureEvidence",
        "closureEvidenceAdversarialStore",
        "closureEvidenceAdversarialStoreEx",
        "closureEvidenceBase",
        "closureEvidenceBaseEx",
        "closureEvidenceC3Duo",
        "closureEvidenceCornerFailoverDuo",
        "closureEvidenceDuo",
        "closureEvidenceFailover",
        "closureEvidenceFailoverDuo",
        "closureEvidenceFailoverEx",
        "closureEvidenceFaultPersist",
        "closureEvidenceFaultPersistEx",
        "closureEvidenceReapTruncate",
        "closureEvidenceSlice",
        "closureEvidenceStaleDuo",
        "closureEvidenceStaleTenure",
        "closureEvidenceSurvivors",
        "closureEvidenceSurvivorsFailover",
        "controller028TruncatedPrune",
        "controller073Burst",
        "controller075FailopenSpawnClobber",
        "controllerCalib113RespawnCancel",
        "controllerCalib113RespawnCancelHold",
        "costLatch",
        "costLatchBase",
        "costlatchCalib212AcquireOnly",
        "ctrlCalib282BackoffIgnored",
        "executorCalibF4PullEstablishEarly",
        "executorSession",
        "executorSessionBase",
        "executorSessionFaultLeader",
        "fenceCalib011AbsoluteReplay",
        "fenceCalib155ServeAfterFailedRecovery",
        "fenceCalib231UnfencedClose",
        "fenceCalib261UnguardedUpsert",
        "fenceCalib273PlainFloorSet",
        "fenceCalib338AtomicReread",
        "fenceCalib393TerminalRefusal",
        "fenceCalibFloorBlind",
        "fencedWrites",
        "fencedWritesT1",
        "ffdCalibNoClassClamp",
        "gaCalibCrdAbsentArmed",
        "gaCalibNoLiveRecheck",
        "gaCalibOrphanGateEmptyOk",
        "gbCalibAckAttempted",
        "gbCalibAckOnlyNew",
        "gcCadence",
        "gcCadenceCalibHourlyRetry",
        "gcCadenceCalibReleaseFailsCommit",
        "gcCadenceCalibSharedClockAnchor",
        "gcCadenceCalibTickBeforeCommit",
        "gcCadenceCalibZeroRowsClaimsForeign",
        "gcCadenceMain",
        "gcCollectState",
        "gcCollectStateCalibSimBasis",
        "gcCollectStateMain",
        "gcCoordination",
        "gcCoordinationLocalTimers",
        "gcCoordinationMain",
        "gcDrainPass",
        "gcDrainPassCalibResumeAnchors",
        "gcDrainPassMain",
        "ggCalibTerminatingPending",
        "gwBuildResync",
        "gwCalibF10AcceptErrorFatal",
        "gwCalibF10AsBuilt",
        "gwCalibF1AsBuilt",
        "gwCalibF1AsBuiltCap1",
        "gwCalibF1AsBuiltSpread",
        "gwCalibF1AuthRejectSkipsGate",
        "gwCalibF1NoGlobalSessionCap",
        "gwCalibF1PerConnCapRefusals",
        "gwCalibF1ServerSideKeepsGuard",
        "gwCalibF2AsBuilt",
        "gwCalibF2NoHandshakeDeadline",
        "gwCalibF2OpenDisarmsGrace",
        "gwCalibF3AsBuilt",
        "gwCalibF3DecideWithoutArm",
        "gwCalibF4AsBuilt",
        "gwCalibF4AsBuiltChanCap1",
        "gwCalibF4BoundOnSessionsMap",
        "gwCalibF4ForgedCloseDecrements",
        "gwCalibF4RefusePolitely",
        "gwCalibF5AsBuilt",
        "gwCalibF5BudgetIgnoresPeerClass",
        "gwCalibF5NoSendBudget",
        "gwCalibF5ReleaseAfterCloseOut",
        "gwCalibF5UnwindowedSend",
        "gwCalibF6AbortWinsOverCancel",
        "gwCalibF6AsBuilt",
        "gwCalibF6CloseOutSkipsExitStatus",
        "gwCalibF6ConnDropLeaksGauge",
        "gwCalibF6ExitEdgeSkipsCancel",
        "gwCalibF6FinishSkipsPumpReap",
        "gwCalibF6WireErrorRemovesTracked",
        "gwCalibF7AcceptStopKillsEstablished",
        "gwCalibF7AsBuilt",
        "gwCalibF7DrainExpiryNoCancel",
        "gwCalibF7SigtermSkipsStages",
        "gwCalibF9AsBuilt",
        "gwCalibF9RpcWaitNoDeadline",
        "gwConnLifecycle",
        "gwConnLifecycleBase",
        "gwConnLifecycleBaseSlim",
        "gwConnLifecycleCap",
        "gwConnLifecycleFamAdmission",
        "gwConnLifecycleFamCap",
        "gwConnLifecycleFamDegraded",
        "gwConnLifecycleFamDrain",
        "gwConnLifecycleFamHostile",
        "gwConnLifecycleFamPreauth",
        "gwConnLifecycleFamUpstream",
        "gwConnLifecycleFamWedge",
        "gwConnLifecycleFaultDegraded",
        "gwConnLifecycleFaultDrain",
        "gwConnLifecycleFaultOccupancy",
        "gwConnLifecycleFaultTransport",
        "gwConnLifecycleFaultUpstream",
        "gwResyncCalibConsumeWhileOwed",
        "gwResyncCalibResetOnSnapshot",
        "gwResyncKindBlind",
        "gwResyncNoPgFallback",
        "gwResyncNoSignal",
        "gwResyncTwoMap",
        "iceCalibApplyBeforeRefuse",
        "iceCalibLatestWinsEviction",
        "iceCalibNoEpochGate",
        "iceEvidenceAck",
        "iceEvidenceAckBase",
        "leaseCalib002ActFailedFrozenNoClear",
        "leaseCalib002StaleDeferral",
        "leaseCalib085BlindConflictLose",
        "leaseCalib096ResponseAnchor",
        "leaseCalib128CountKeyedStepDown",
        "leaseCalib138EdgeOnly",
        "leaseCalib180RvKeyed",
        "leaseCalib181BoolClear",
        "leaseCalib303BlindTimeout",
        "leaseCalib387BeliefGate",
        # bughunt-13 OP-6 stage 3: the logService plane (30 modules --
        # 26 logService* + 4 logIngest*) left the grandfather; every
        # wired step action carries a live-verified binding.
        "m1CalibAcquireClearOkOnly",
        "m1CalibReapBusyGuardProbe",
        "m2CalibInflightDropOnSight",
        "m2CalibNoConsolidatePrune",
        "m34CalibLatchClearOnAttempt",
        "m34CalibNoRecencyGate",
        "matCalib133DiscardedOutcome",
        "matCalib146ControllerCrossKindClose",
        "matCalib233UnattributedPin",
        "matCalib266KindblindRecoveryHolder",
        "matCalib276DagAbsentCancel",
        "matCalib318RequeueForcesReady",
        "matCalibAbortCharges",
        "matCalibB1ClaimRefusesMarked",
        "matCalibB2NoPinAtIngest",
        "matCalibB3NoRedial",
        "matCalibB4NoBackfill",
        "matCalibB5aRefeedOverwrite",
        "matCalibCe17SkipCoverage",
        "matCalibChainResetDropsCarrier",
        "matCalibChainResetDropsCarrierEx",
        "matCalibChargeOnCancel",
        "matCalibCollidingIdentity",
        "matCalibDedupRemoved",
        "matCalibEstablishNeverParks",
        "matCalibExistsgateForallstamp",
        "matCalibF10FailoverViewDrop",
        "matCalibF10bSwallowedRebuild",
        "matCalibF11UnfencedResolve",
        "matCalibF1NoPresenceRecheck",
        "matCalibF2bEstablishAdopt",
        "matCalibF3InfraAsUnobtainable",
        "matCalibF3ParkFailFast",
        "matCalibF3pUnsoundReport",
        "matCalibF4DeadUnion",
        "matCalibF5WantedOverwrite",
        "matCalibF7UnkeyedResolve",
        "matCalibF8PullIgnoresJob",
        "matCalibF9DivergentEvidence",
        "matCalibFailoverDropsRows",
        "matCalibHeadStarvation",
        "matCalibInloopReturn",
        "matCalibLeafParkForever",
        "matCalibPp4EstablishBuildCharge",
        "matCalibPp4EstablishUncharged",
        "matCalibProbeCharged",
        "matCalibRefsFolded",
        "matCalibSplitRearm",
        "matCalibTenantblindPresent",
        "matCalibTransientAsInfra",
        "matCalibUnionDropped",
        "matCalibUnscopedCount",
        "matCalibVacuousSuccess",
        "matCalibWholesetProjection",
        "matDistCalibDeadHeadPinsWindow",
        "matDistCalibEagerSteal",
        "matDistCalibNoStealOrphan",
        "matDistCalibOwnerServeSkew",
        "matDistCalibSharedHeadConvoy",
        "matDistCalibWedgedPoller",
        "materializationDistribution",
        "materializationDistributionBase",
        "materializationDistributionDead",
        "materializationDistributionWedge",
        "materializationJobAdversarialStore",
        "materializationJobAdversarialStoreEx",
        "materializationJobBase",
        "materializationJobBaseEx",
        "materializationJobCrashLoop",
        "materializationJobCrashLoopEx",
        "materializationJobFailover",
        "materializationJobFailoverEx",
        "materializationJobResolveFaults",
        "materializationJobStaleTenure",
        "materializationJobStaleTenureEx",
        "materializationJobWalkFold",
        "materializationJobWorkerAbort",
        "nCalibRetiredCap",
        "nodeclaimLifecycle",
        "nodeclaimLifecycleAckLatchAsBuilt",
        "nodeclaimLifecycleBase",
        "nodeclaimLifecycleClearBuffer",
        "nodeclaimLifecycleClearBufferAsBuilt",
        "nodeclaimLifecycleDefer",
        "nodeclaimLifecycleDeferAsBuilt",
        "nodeclaimLifecycleEpoch",
        "nodeclaimLifecycleEpochAsBuilt",
        "nodeclaimLifecycleFaultKarpenter",
        "nodeclaimLifecycleFaultLease",
        "nodeclaimLifecycleFaultRpc",
        "nodeclaimLifecycleSnapshot",
        "nodeclaimLifecycleSnapshotAsBuilt",
        "nodeclaimLifecycleTombstone",
        "nodeclaimLifecycleTombstoneAsBuilt",
        "nodeclaimLifecycleTombstoneDisposition",
        "nodeclaimLifecycleTombstoneDispositionAsBuilt",
        "openAttempts",
        "openAttemptsAckOnFailedClose",
        "openAttemptsBudget",
        "openAttemptsChargeBlind",
        "openAttemptsClobberedCredential",
        "openAttemptsMintingConfirm",
        "openAttemptsNoFallbackRelease",
        "openAttemptsNoncelessMint",
        "openAttemptsOutboxDropped",
        "openAttemptsOvermint",
        "openAttemptsRefusalAsLost",
        "openAttemptsRotationSkew",
        "openAttemptsUnfencedGone",
        "placeholderClaim",
        "placeholderClaimMain",
        "placeholderClaimNoLiveness",
        "placeholderClaimNoPhase",
        "placeholderClaimSubHeartbeatWindow",
        "refcountCalibG1CompletionUnclaimGated",
        "refcountCalibG1ReapPathMatched",
        "refcountCalibG1RollbackPreToken",
        "refcountCalibG2ReapInlineOnly",
        "refcountCalibG2SweepCollapsedCount",
        "refcountCalibG3CounterAsPresence",
        "refcountCalibG3JointStaleSkip",
        "refcountCalibG4aDrainNoRecheck",
        "refcountCalibG5NoHeartbeat",
        "refcountCalibG5NoHotpathReclaim",
        "refcountCollectG1CompletionUnclaimGated",
        "refcountCollectG4aDrainNoRecheck",
        "refcountCollectG5Baseline",
        "refcountCollectG5NoHeartbeat",
        "respawnGiveUp",
        "respawnGiveUpAsBuilt",
        "respawnGiveUpCore",
        "respawnGiveUpOrderKeyed",
        "retryCalibForkedRun",
        "retryCalibGuardVacuous",
        "retryCalibSdAsInfra",
        "retryCalibUnboundedDegraded",
        # bughunt-13 OP-6 stage 1 (F14): the retryPolicy plane left the
        # grandfather — every step-referenced action carries a
        # grammar-valid Mirrors:/Environment: binding verified against
        # the live tree (the dead spawn_substitute pointer, the
        # audit's exhibit 1, died with the conversion).
        "spawnCoherence",
        "spawnCoherenceBase",
        "spawnCoherenceCancelAsBuilt",
        "spawnCoherenceCancelCause",
        "spawnCoherenceCancelGenAsBuilt",
        "spawnCoherenceCancelGeneration",
        "spawnCoherenceCrdAbsent",
        "spawnCoherenceExhaustAsBuilt",
        "spawnCoherenceExhaustPersist",
        "spawnCoherenceFailopenWithhold",
        "spawnCoherenceFaultLease",
        "spawnCoherenceFaultRpc",
        "spawnCoherenceFaultStale",
        "spawnCoherenceFetcher",
        "spawnCoherenceHeld",
        "spawnCoherenceHeldAsBuilt",
        "spawnCoherenceMatJobs",
        "spawnCoherenceMultiPool",
        "spawnCoherenceMultiPoolAsBuilt",
        "spawnCoherenceReapYoungLeader",
        "spawnCoherenceRenderedDeadline",
        "spawnCoherenceRetryBackoff",
        "spawnCoherenceStreakCadence",
        "spawnCoherenceSynthCloseAsBuilt",
        "spawnCoherenceSynthClosePinned",
        "tailReaderCalibOrphanHotloop",
        "tailReaderCalibResetOnReceipt",
        "tailReaderLoop",
        "walkFanout",
        "walkFanoutArrivalPick",
        "walkFanoutDupFrontier",
        "walkFanoutProgress",
        "walkFanoutProgressBaseCapture",
        "walkFanoutSpawnAfterAbort",
        "walkFanoutSpawnUnbounded",
        "wedge023DowngradeSkipsClose",
        "wedge023DowngradeSkipsCloseHold",
        "wedgeCalib009SplitPopulation",
        "wedgeCalib016SuppressedDrain",
        "wedgeCalib023OpenRelease",
        "wedgeCalib024GhostAdmission",
        "wedgeCalib034Instantaneous",
        "wedgeCalib163PartialDrain",
        "wedgeCalib176EarlyReturn",
        "wedgeCluster",
        "wedgeClusterAdmission",
        "wedgeClusterDwellArm",
        "wedgeClusterEpilogue",
        "wedgeClusterLatch",
        "wedgeClusterMain",
        "wedgeClusterNoEviction",
        "wedgeClusterTrajectory",
    }
)

HOLDS_KINDS = {"holds", "holds-sim"}

# P7 grandfather allowlist — GENERATED, FROZEN at the round-6 WO-S8-4
# conversion (banner rule 1: membership is the P7 pass's own output
# over the conversion-time corpus, never author-typed). Generator:
# this script's P7 arm with an empty allowlist over the wired corpus
# at the conversion tree (the quint-policy derivation's violation
# print, deduped on (module, leaf)); the pairs are frozen verbatim
# below. The matdist bundle is ABSENT by construction — it was split
# in the same landing (the bug_087 close), so the conversion census
# is the post-split corpus. Burn-down owned by round-7 (split each
# into named val leaves, then delete its row); NEW entries require a
# wave ruling — adding one here without a ruling is the violation P7
# exists to catch.
P7_GRANDFATHER: frozenset = frozenset(
    {
        ("authz", "enforcementFromDeclaredVerifiersOnly"),
        ("chunkCollect", "boundsOK"),
        ("chunkCollect", "cr1NoLiveChunkCollected"),
        ("chunkCollect", "cr4PresenceFromConfirmedUpload"),
        ("chunkLiveness", "boundsOK"),
        ("chunkLiveness", "cr1NoLiveChunkCollected"),
        ("chunkLiveness", "cr4PresenceFromConfirmedUpload"),
        ("costLatch", "boundsOK"),
        ("executorSession", "atMostOneOpenAttemptPerJob"),
        ("executorSession", "attemptResolvesAtMostOnce"),
        ("executorSession", "noFabricatedCompletion"),
        ("executorSession", "notYetReadyIsInert"),
        ("gcCoordination", "gcBoundsOK"),
        ("gwBuildResync", "boundedResyncStreak"),
        ("gwConnLifecycle", "boundsOK"),
        ("gwConnLifecycle", "p5CompliantPeerNotForceClosed"),
        ("gwConnLifecycle", "s11ForceCloseArmedSticky"),
        ("gwConnLifecycle", "s13WindowPacedEgress"),
        ("gwConnLifecycle", "s17DrainStageOrder"),
        ("gwConnLifecycle", "s1ConnPermitConservation"),
        ("gwConnLifecycle", "s2SessionPermitConservation"),
        ("gwConnLifecycle", "s3GaugeAccuracy"),
        ("gwConnLifecycle", "s7ChannelAccounting"),
        ("gwConnLifecycle", "s9SingleRelease"),
        ("leaderElection", "boundsOK"),
        ("leaderMarks", "boundsOK"),
        ("logIngestLiveness", "boundsOK"),
        ("logService", "boundsOK"),
        ("logService", "readerBoundsOK"),
        ("logService", "servedStreamSpanExact"),
        ("materializationJob", "boundsOK"),
        # bw10 WO-S8-5 ruling (merged_bug_090's re-scan duty): the
        # unified refusal predicate surfaced this MIXED bundle (1
        # anonymous forall + 1 named conjunct) that the old anon>=2
        # gate never saw — visible across all 8 materialization-holds
        # checks. The model-plane fix (split into named leaves + per-
        # leaf P1 twins) is docs/spec/models work outside this wave's
        # S8 grant (models are S4-sole this round, §1.6.3); recorded
        # here per the WO's fixed-or-twinned-RECORDED arm so the
        # bundle is a visible census row instead of an invisible
        # laundering. Burn-down trigger: the next materializationJob
        # model pass splits the leaf and deletes this row.
        ("materializationJob", "noWrongfulTerminalFailure"),
        ("nodeclaimLifecycle", "boundsOK"),
        ("nodeclaimLifecycle", "degradedCoverPolarity"),
        ("nodeclaimLifecycle", "provisioningBudget"),
        ("openAttempts", "cancelledNeverChargedAsCrash"),
        ("openAttempts", "claimedImpliesOpenAttempt"),
        ("placeholderClaim", "boundsOK"),
        ("retryPolicy", "attemptsChargedOnce"),
        ("retryPolicy", "boundsOK"),
        ("retryPolicy", "cascadeReachesExactlyTheDependents"),
        ("retryPolicy", "poisonIsTerminalUntilCleared"),
        ("retryPolicy", "recoveryNeverFabricatesFailures"),
        ("retryPolicy", "verdictMatchesFold"),
        ("wedgeCluster", "boundsOK"),
        ("wedgeCluster", "markedIncrementsOnlyOnEdges"),
    }
)
WITNESS_KINDS = {"witness", "witness-sim"}


def fail(msg):
    print(f"quint-policy: FATAL: {msg}", file=sys.stderr)
    sys.exit(2)


def canary(ir_dir: Path):
    """Pin the quint IR shape on a known fixture parsed in-derivation."""
    p = ir_dir / "__canary__.json"
    if not p.exists():
        fail("IR canary fixture missing — derivation must parse the canary model")
    ir = json.loads(p.read_text())
    try:
        mods = ir["modules"]
        m = next(mm for mm in mods if mm["name"] == "policyCanary")
        decls = m["declarations"]
        kinds = {d["kind"] for d in decls}
        assert "var" in kinds and "def" in kinds, kinds
        act = next(d for d in decls if d.get("qualifier") == "action" and d["name"] == "step")
        assigns = []

        def walk(e):
            if isinstance(e, dict):
                if e.get("kind") == "app" and e.get("opcode") == "assign":
                    assigns.append(e)
                for v in e.values():
                    walk(v)
            elif isinstance(e, list):
                for v in e:
                    walk(v)

        walk(act["expr"])
        assert assigns, "canary step has no assign apps"
        a0 = assigns[0]
        assert a0["args"][0]["kind"] == "name", a0
    except (KeyError, StopIteration, AssertionError) as e:
        fail(f"quint IR shape drifted (canary mismatch: {e!r}) — update quint_policy.py for the new IR before trusting any verdict")


class Corpus:
    def __init__(self, ir_dir: Path, models_dir: Path):
        self.mod_file = {}        # module -> declaring file (rel)
        self.mod_decls = {}       # module -> {name: decl}
        self.mod_imports = defaultdict(set)   # module -> imported/instanced module names
        self.file_modules = defaultdict(list)  # rel file -> [modules declared]
        self.latch_directives = {}  # module -> [vars]
        mod_re = re.compile(r"^\s*module\s+(\w+)\s*\{", re.M)
        latch_re = re.compile(r"^\s*//\s*quint-policy-latches:\s*(.+)$", re.M)
        for f in sorted(models_dir.rglob("*.qnt")):
            rel = str(f.relative_to(models_dir))
            text = f.read_text()
            mods_here = mod_re.findall(text)
            self.file_modules[rel] = mods_here
            for m in latch_re.findall(text):
                vars_ = [v.strip() for v in m.split(",") if v.strip()]
                # directive binds to the first module of the file (live
                # models are single-module-first by corpus convention)
                if mods_here:
                    self.latch_directives.setdefault(mods_here[0], []).extend(vars_)
            for mn in mods_here:
                if mn in self.mod_file:
                    fail(f"module {mn} declared in both {self.mod_file[mn]} and {rel}")
                self.mod_file[mn] = rel
        # IR: one json per file, named <relpath with / -> __>.json
        for f in sorted(ir_dir.glob("*.json")):
            if f.name == "__canary__.json":
                continue
            ir = json.loads(f.read_text())
            for m in ir.get("modules", []):
                name = m["name"]
                if name in self.mod_decls:
                    continue  # same module reached through several parses
                decls = {}
                imports = set()
                for d in m.get("declarations", []):
                    k = d.get("kind")
                    if k in ("import", "instance"):
                        pn = d.get("protoName") or d.get("name")
                        if pn:
                            imports.add(pn)
                    elif "name" in d:
                        decls[d["name"]] = d
                self.mod_decls[name] = decls
                self.mod_imports[name] = imports
        self._reach_cache = {}
        self._readset_cache = {}

    def reachable_modules(self, mod):
        if mod in self._reach_cache:
            return self._reach_cache[mod]
        seen, stack = set(), [mod]
        while stack:
            m = stack.pop()
            if m in seen or m not in self.mod_imports and m not in self.mod_decls:
                seen.add(m)
                continue
            seen.add(m)
            stack.extend(self.mod_imports.get(m, ()) - seen)
        self._reach_cache[mod] = seen
        return seen

    def visible_decl(self, mod, name):
        """Lexical lookup: own decls first, then reached modules' —
        and cross-module ambiguity is FATAL (bug_094). The old code
        iterated `reachable_modules` (a plain set), so twin credit and
        writer verdicts depended on PYTHONHASHSEED whenever a name was
        declared in 2+ co-reachable modules: the same corpus flipped
        between `violations: 0` and `violations: 1` across seeds. A
        merge gate's verdict must be a pure function of the corpus."""
        d = self.mod_decls.get(mod, {}).get(name)
        if d is not None:
            return mod, d
        owners = sorted(
            m
            for m in self.reachable_modules(mod)
            if m != mod and name in self.mod_decls.get(m, {})
        )
        if len(owners) > 1:
            fail(
                f"ambiguous name '{name}' seen from module '{mod}': declared in "
                f"{', '.join(owners)} — rename or qualify; lint resolution must "
                f"never depend on set-iteration order (bug_094)"
            )
        if owners:
            return owners[0], self.mod_decls[owners[0]][name]
        return None, None

    @staticmethod
    def _names_in(expr, acc):
        if isinstance(expr, dict):
            if expr.get("kind") == "name":
                acc.add(expr["name"])
            # user-defined operator APPLICATION: the IR encodes it as
            # app.opcode = <operator name> (builtin opcodes simply fail
            # decl lookup downstream — harmless)
            if expr.get("kind") == "app" and expr.get("opcode"):
                acc.add(expr["opcode"])
            if expr.get("kind") == "lambda":
                pass  # params shadow, but params aren't state vars; fine
            for v in expr.values():
                Corpus._names_in(v, acc)
        elif isinstance(expr, list):
            for v in expr:
                Corpus._names_in(v, acc)

    def var_readset(self, mod, name):
        """Transitive state-var read-set of declaration `name` seen from `mod`.
        Returns {(declaring_module, var)}."""
        key = (mod, name)
        if key in self._readset_cache:
            return self._readset_cache[key]
        self._readset_cache[key] = set()  # cycle guard
        dmod, d = self.visible_decl(mod, name)
        out = set()
        if d is None:
            self._readset_cache[key] = out
            return out
        if d["kind"] == "var":
            out.add((dmod, name))
        elif d["kind"] in ("def",):
            refs = set()
            self._names_in(d.get("expr"), refs)
            for r in refs:
                if r == name:
                    continue
                out |= self.var_readset(dmod, r)
        self._readset_cache[key] = out
        return out

    def conj_expansion(self, mod, leaf):
        """THE expansion capability test (merged_bug_090): the single
        predicate BOTH the twin engine (`conj_leaves`) and the P7 gate
        consume — P7 is DEFINED as this function's refusal, so the ban
        and the engine cannot drift (the old gate re-derived a
        narrower predicate: anon>=2 after a let unwrap, which let a
        MIXED bundle [anon=1] and a LET-WRAPPED all-name bundle
        [anon=0] each ship as one opaque leaf earning
        intersection-based twin credit over the merged read-set — the
        bug_087 shape P7 exists to ban). Returns one of:
          ("atom", None)         — body is not a conjunction (or an
                                   empty one): a true leaf;
          ("expanded", names)    — a bare all-name and/actionAll: the
                                   engine recurses through it;
          ("refused", detail)    — conjunction-shaped but NOT
                                   expandable (anonymous operands
                                   and/or a let wrapper): ships as ONE
                                   opaque leaf; exactly what P7 bans.
        detail = {"anon": n, "named": n, "lets": n}."""
        dmod, d = self.visible_decl(mod, leaf)
        if d is None or d["kind"] != "def":
            return ("atom", None)
        e = d.get("expr")
        lets = 0
        inner = e
        while isinstance(inner, dict) and inner.get("kind") == "let":
            lets += 1
            inner = inner.get("expr")
        if not (
            isinstance(inner, dict)
            and inner.get("kind") == "app"
            and inner.get("opcode") in ("and", "actionAll")
        ):
            return ("atom", None)
        args = inner.get("args", [])
        if not args:
            return ("atom", None)
        anon = sum(1 for a in args if not (isinstance(a, dict) and a.get("kind") == "name"))
        if lets == 0 and anon == 0:
            return ("expanded", [a["name"] for a in args])
        return ("refused", {"anon": anon, "named": len(args) - anon, "lets": lets})

    def conj_leaves(self, mod, inv):
        """Expand a conjunction val to leaf val names via
        [`conj_expansion`]; an atom or a REFUSED expansion is its own
        leaf (the P7 gate consumes the same predicate, so every
        refused leaf in this output is flagged there — the complement
        is structural, not re-derived)."""
        dmod, d = self.visible_decl(mod, inv)
        if d is None or d["kind"] != "def":
            return [(mod, inv)]
        verdict, payload = self.conj_expansion(mod, inv)
        if verdict == "expanded":
            leaves = []
            for name in payload:
                leaves.extend(self.conj_leaves(dmod, name))
            return leaves
        return [(dmod, inv)]

    def assigns_reachable(self, mod, roots):
        """All assign apps in defs reachable (by name reference) from root decl names in mod.
        Returns [(target_var, rhs_is_identity)]."""
        seen, stack, out = set(), list(roots), []
        while stack:
            nm = stack.pop()
            if nm in seen:
                continue
            seen.add(nm)
            dmod, d = self.visible_decl(mod, nm)
            if d is None or d["kind"] != "def":
                continue

            def walk(e):
                if isinstance(e, dict):
                    if e.get("kind") == "app" and e.get("opcode") == "assign":
                        tgt = e["args"][0].get("name")
                        rhs = e["args"][1]
                        ident = isinstance(rhs, dict) and rhs.get("kind") == "name" and rhs.get("name") == tgt
                        out.append((tgt, ident))
                    if e.get("kind") == "name":
                        stack.append(e["name"])
                    if e.get("kind") == "app" and e.get("opcode"):
                        stack.append(e["opcode"])
                    for v in e.values():
                        walk(v)
                elif isinstance(e, list):
                    for v in e:
                        walk(v)

            walk(d.get("expr"))
        return out

    def module_action_names(self, mod):
        return [n for n, d in self.mod_decls.get(mod, {}).items() if d.get("qualifier") == "action"]

    def action_binding(self, mod, action, models_dir):
        """The P8 binding of `action` as declared in `mod`'s file:
        ("mirrors", [(file, symbol), ...]), ("environment", text), or
        None. Text-plane declared configuration (the latches-directive
        precedent): the binding lives in the contiguous comment block
        directly above the action declaration."""
        rel = self.mod_file.get(mod)
        if rel is None:
            return None
        if not hasattr(self, "_file_lines"):
            self._file_lines = {}
        if rel not in self._file_lines:
            self._file_lines[rel] = (models_dir / rel).read_text().splitlines()
        lines = self._file_lines[rel]
        decl_re = re.compile(rf"^\s*action\s+{re.escape(action)}\b")
        mirrors_re = re.compile(r"^\s*//+\s*Mirrors:\s*(\S+?):([A-Za-z_][A-Za-z0-9_]*)\s*$")
        env_re = re.compile(r"^\s*//+\s*Environment:\s*(\S.*)$")
        comment_re = re.compile(r"^\s*//")
        for i, line in enumerate(lines):
            if not decl_re.match(line):
                continue
            mirrors, env = [], None
            j = i - 1
            while j >= 0 and comment_re.match(lines[j]):
                m = mirrors_re.match(lines[j])
                if m:
                    mirrors.append((m.group(1), m.group(2)))
                e = env_re.match(lines[j])
                if e and env is None:
                    env = e.group(1)
                j -= 1
            if mirrors:
                return ("mirrors", list(reversed(mirrors)))
            if env is not None:
                return ("environment", env)
            return None
        return None


def run_policy(manifest, corpus, assume_latches="", models_dir=None, mirrors_root=None):
    """The P1–P6 rule engine over a parsed corpus → (violations, census).

    Pure in/out (no I/O beyond the corpus already parsed) so the
    in-derivation self-test can drive planted corpora through the SAME
    arms the live gate runs — a rule that cannot fail a fixture is
    dead code by construction (merged_bug_090's P6 arm was exactly
    that: condition computed, body `pass`)."""

    def is_calib_module(mod):
        f = corpus.mod_file.get(mod, "")
        return f.startswith("calibration/")

    # provisional latches for census
    for part in filter(None, assume_latches.split(";")):
        m, vs = part.split(":", 1)
        corpus.latch_directives.setdefault(m, []).extend(v.strip() for v in vs.split(","))

    violations, census = [], defaultdict(list)
    exemptions_used = set()

    # ---- R0 reconciliation: wired == discovered. Every non-null
    # manifest entry's main module must exist in the parsed IR and
    # every wired invariant/witness name must resolve — a check wired
    # against a missing or renamed module otherwise degrades to
    # silently-vacuous credit (fail-open). Unwired live modules are
    # censused so coverage holes stay loud.
    unresolved = set()
    for cname, meta in sorted(manifest.items()):
        if not meta:
            continue
        main_mod = meta.get("main")
        if main_mod not in corpus.mod_decls:
            violations.append(
                f"R0 {cname}: main module '{main_mod}' not found in parsed IR (wired-but-missing)"
            )
            census["R0-missing-main"].append(cname)
            continue
        for inv in meta.get("invariants") or []:
            if corpus.visible_decl(main_mod, inv) == (None, None):
                violations.append(
                    f"R0 {cname}: invariant '{inv}' does not resolve from main '{main_mod}'"
                )
                census["R0-missing-inv"].append(f"{cname}:{inv}")
                unresolved.add((cname, inv))
        w = meta.get("witness")
        if w and meta.get("kind") in WITNESS_KINDS and corpus.visible_decl(main_mod, w) == (None, None):
            violations.append(
                f"R0 {cname}: witness '{w}' does not resolve from main '{main_mod}'"
            )
            census["R0-missing-witness"].append(f"{cname}:{w}")
    reached_live = set()
    for _cname, meta in manifest.items():
        if meta and meta.get("main") in corpus.mod_decls:
            for m in corpus.reachable_modules(meta["main"]):
                if m in corpus.mod_file and not is_calib_module(m):
                    reached_live.add(m)
    for m in sorted(set(corpus.mod_file) - reached_live):
        if not is_calib_module(m):
            census["R0-unwired-live-module"].append(m)

    # ---- index witness checks: (live modules reached, witness var read-set)
    witnesses = []
    for cname, meta in sorted(manifest.items()):
        if not meta or meta.get("kind") not in WITNESS_KINDS:
            continue
        main_mod = meta["main"]
        reach = corpus.reachable_modules(main_mod)
        live_reach = {m for m in reach if m in corpus.mod_file and not is_calib_module(m)}
        wreads = corpus.var_readset(main_mod, meta["witness"])
        witnesses.append((cname, meta, main_mod, live_reach, wreads))

    # ---- P2: frozen copies + def-flip shadowing (witness + run mains)
    for cname, meta in sorted(manifest.items()):
        if not meta or meta.get("kind") not in (WITNESS_KINDS | {"run"}):
            continue
        main_mod = meta["main"]
        if main_mod not in corpus.mod_decls:
            continue  # R0 already reported wired-but-missing
        if not is_calib_module(main_mod):
            continue  # live-file mains are their own model
        reach = corpus.reachable_modules(main_mod)
        live_reach = {m for m in reach if m != main_mod and m in corpus.mod_file and not is_calib_module(m)}
        if not live_reach:
            violations.append(f"P2 {cname}: calibration main '{main_mod}' imports NO live model (frozen copy)")
            census["P2-frozen-copy"].append(cname)
            continue
        own = corpus.mod_decls[main_mod]
        live_names = set()
        for m in live_reach:
            for n, d in corpus.mod_decls[m].items():
                if d.get("qualifier") != "action":
                    live_names.add(n)
        for n, d in own.items():
            if d["kind"] == "def" and d.get("qualifier") != "action" and n in live_names:
                violations.append(f"P2 {cname}: calibration '{main_mod}' shadows live non-action declaration '{n}' (def-flip)")
                census["P2-shadow"].append(f"{cname}:{n}")

    # ---- P1 + P4 over holds checks
    p4_checked = set()
    for cname, meta in sorted(manifest.items()):
        if not meta or meta.get("kind") not in HOLDS_KINDS:
            continue
        main_mod = meta["main"]
        if main_mod not in corpus.mod_decls:
            continue  # R0 already reported wired-but-missing
        exempts = meta.get("vacuityExempt") or {}
        for cls in {e.get("class") for e in exempts.values() if isinstance(e, dict)}:
            if cls not in EXEMPT_CLASSES:
                violations.append(f"P6 {cname}: unknown vacuityExempt class '{cls}'")
        for inv in meta.get("invariants") or []:
            if (cname, inv) in unresolved:
                continue  # R0 reported it; a P1-tautology label would mislead
            for lmod, leaf in corpus.conj_leaves(main_mod, inv):
                reads = corpus.var_readset(lmod, leaf)
                ex = exempts.get(leaf) or exempts.get(inv)
                # P7: unexpandable conjunction bundles are banned —
                # the bundle defeats P1's per-leaf twin engine
                # (bug_087). The ban IS the expansion engine's own
                # refusal (merged_bug_090: one predicate, drift
                # unrepresentable) — every leaf in conj_leaves' output
                # is an atom or a refusal, and refusals are flagged.
                verdict, detail = corpus.conj_expansion(lmod, leaf)
                if verdict == "refused":
                    if (lmod, leaf) in P7_GRANDFATHER:
                        census["P7-grandfathered"].append(f"{cname}:{lmod}.{leaf}")
                    else:
                        shape = []
                        if detail["anon"]:
                            shape.append(f"{detail['anon']} anonymous")
                        if detail["named"]:
                            shape.append(f"{detail['named']} named")
                        if detail["lets"]:
                            shape.append("let-wrapped")
                        violations.append(
                            f"P7 {cname}: invariant leaf '{leaf}' ({lmod}) is an unexpandable "
                            f"conjunction bundle ({', '.join(shape)}) — the twin engine refuses "
                            "to expand it, so it ships as ONE opaque leaf with merged-read-set "
                            "twin credit; split into named val leaves (each then owes its own "
                            "P1 falsify twin); grandfather entries are frozen generator output "
                            "and new ones require a wave ruling"
                        )
                        census["P7-anonymous-bundle"].append(f"{cname}:{lmod}.{leaf}")
                if not reads:
                    violations.append(
                        f"P1 {cname}: invariant leaf '{leaf}' has an EMPTY var read-set (tautology) — restate over the transition relation; not exemptable")
                    census["P1-tautology"].append(f"{cname}:{leaf}")
                    continue
                live_mods = {m for (m, _) in reads}
                twins = [
                    wname for (wname, _, _, wlive, wreads) in witnesses
                    if (wlive & live_mods) and (wreads & reads)
                ]
                if twins:
                    census["P1-twinned"].append(f"{cname}:{leaf}")
                elif ex and isinstance(ex, dict) and ex.get("class") in EXEMPT_CLASSES and ex.get("reason"):
                    census[f"exempt-{ex['class']}"].append(f"{cname}:{leaf} — {ex['reason']}")
                    exemptions_used.add((cname, leaf if leaf in exempts else inv))
                else:
                    violations.append(
                        f"P1 {cname}: invariant leaf '{leaf}' (vars {sorted(v for _, v in reads)}) has no live-importing read-set-matched falsify twin and no vacuityExempt")
                    census["P1-untwinned"].append(f"{cname}:{leaf}")
                # P4 per (module, var): rooted at the LIVE module's own
                # step — the module declaring the var (spec wording; a
                # regime override may legitimately disable alphabets, so
                # the writer obligation belongs to the live model).
                # Fallback for legacy step-less modules: all of the
                # module's actions (hazard (nn)).
                for (vmod, var) in sorted(reads):
                    if (vmod, var) in p4_checked:
                        continue
                    p4_checked.add((vmod, var))
                    roots = (
                        ["step"]
                        if "step" in corpus.mod_decls.get(vmod, {})
                        else corpus.module_action_names(vmod)
                    )
                    writes = corpus.assigns_reachable(vmod, roots)
                    if not any(t == var and not ident for (t, ident) in writes):
                        violations.append(
                            f"P4 {cname}: var '{vmod}.{var}' (read by '{leaf}') has no non-identity assignment reachable from {vmod}.step — writerless latch")
                        census["P4-writerless"].append(f"{vmod}.{var}")

        # P6: unused exemptions are ERRORS (merged_bug_090 — the old
        # body computed its condition then executed an unconditional
        # `pass`, so a stale exemption on a since-twinned leaf survived
        # silently and would re-engage to bypass P1 if the twin rots).
        # Keyed on exemptions_used ALONE: the old census-prefix
        # conjunct hid exactly the re-twinned case.
        for k in sorted(exempts):
            if (cname, k) not in exemptions_used:
                violations.append(
                    f"P6 {cname}: unused vacuityExempt entry '{k}' — the leaf is twinned (or gone); remove the exemption"
                )
                census["P6-unused-exempt"].append(f"{cname}:{k}")

    # ---- P5: latch integrity
    for lmod, latches in sorted(corpus.latch_directives.items()):
        for var in sorted(set(latches)):
            roots = ["step"] if "step" in corpus.mod_decls.get(lmod, {}) else corpus.module_action_names(lmod)
            writes = corpus.assigns_reachable(lmod, roots)
            if not any(t == var and not ident for (t, ident) in writes):
                violations.append(f"P5 {lmod}: declared latch '{var}' fails P4 (no live non-identity writer)")
                census["P5-latch-writerless"].append(f"{lmod}.{var}")
        # calibration writers
        for cmod, decls in corpus.mod_decls.items():
            if not is_calib_module(cmod):
                continue
            if lmod not in corpus.reachable_modules(cmod):
                continue
            # bug_281: runs carry inline anonymous actions (init.then(all
            # { latch' = ... })) — a root set of qualifier=="action" alone
            # left every run-shaped calibration outside the P5 gate, a
            # fail-open arm in a lint documented fail-closed. Both
            # declaration shapes are walked; opting a shape out is now an
            # explicit edit here, not an accident of the root set.
            roots = [n for n, d in decls.items() if d.get("qualifier") in ("action", "run")]
            for var in sorted(set(latches)):
                # only count assigns in the calibration's OWN declarations
                own_writes = []
                for n in roots:
                    d = decls[n]
                    acc = []

                    def walk(e):
                        if isinstance(e, dict):
                            if e.get("kind") == "app" and e.get("opcode") == "assign":
                                tgt = e["args"][0].get("name")
                                rhs = e["args"][1]
                                ident = isinstance(rhs, dict) and rhs.get("kind") == "name" and rhs.get("name") == tgt
                                acc.append((tgt, ident))
                            for v in e.values():
                                walk(v)
                        elif isinstance(e, list):
                            for v in e:
                                walk(v)

                    walk(d.get("expr"))
                    own_writes.extend(acc)
                if any(t == var and not ident for (t, ident) in own_writes):
                    violations.append(f"P5 {cmod}: calibration declaration non-identity-assigns latch '{lmod}.{var}' (oracle must live in the shared live module)")
                    census["P5-calib-latch-write"].append(f"{cmod}:{var}")

    # ---- P8: action bindings over wired step alphabets
    p8_checked = set()
    p8_grandfathered_mods = set()
    for cname, meta in sorted(manifest.items()):
        if not meta or meta.get("main") not in corpus.mod_decls:
            continue
        main_mod = meta["main"]
        step_name = meta.get("step") or "step"
        smod, sdecl = corpus.visible_decl(main_mod, step_name)
        if sdecl is None or sdecl.get("qualifier") != "action":
            continue  # legacy step-less module (hazard (nn)) — P4's fallback domain
        refs = set()
        corpus._names_in(sdecl.get("expr"), refs)
        for nm in sorted(refs):
            # The scheduler dispatcher is the alphabet's frame, never a
            # transition: skip the regime's own step AND the live
            # module's `step` when a calibration step composes over it
            # (the calibStep `any { step, override }` shape) — its
            # alphabet is exactly what this walk enforces.
            if nm == step_name or nm == "step":
                continue
            amod, adecl = corpus.visible_decl(smod, nm)
            if adecl is None or adecl.get("qualifier") != "action":
                continue
            if (amod, nm) in p8_checked:
                continue
            p8_checked.add((amod, nm))
            if amod in P8_GRANDFATHER:
                p8_grandfathered_mods.add(amod)
                continue
            if models_dir is None:
                continue  # census-less invocation (unit shims)
            binding = corpus.action_binding(amod, nm, models_dir)
            if binding is None:
                violations.append(
                    f"P8 {cname}: step action '{nm}' ({amod}) carries no binding — add "
                    f"`// Mirrors: <repo-file>:<symbol>` (the production transition it "
                    f"abstracts) or `// Environment: <justification>` in the comment "
                    f"block above its declaration (the live_061 class: a modeled "
                    f"transition with zero production writers ships invisible)"
                )
                census["P8-unbound-action"].append(f"{amod}.{nm}")
                continue
            kind, payload = binding
            if kind == "environment":
                census["P8-environment"].append(f"{amod}.{nm}")
                continue
            for (mfile, msym) in payload:
                target = None if mirrors_root is None else (mirrors_root / mfile)
                if target is None or not target.is_file():
                    violations.append(
                        f"P8 {cname}: action '{nm}' ({amod}) mirrors '{mfile}:{msym}' but "
                        f"the file does not resolve under the staged mirrors root — a "
                        f"dead pointer is exactly as dead as no pointer"
                    )
                    census["P8-unresolvable-mirror"].append(f"{amod}.{nm}:{mfile}")
                    continue
                text = target.read_text()
                if not re.search(rf"\b{re.escape(msym)}\b", text):
                    violations.append(
                        f"P8 {cname}: action '{nm}' ({amod}) mirrors '{mfile}:{msym}' but "
                        f"the symbol is absent from that file — the production anchor "
                        f"moved or never existed; re-derive the binding"
                    )
                    census["P8-unresolvable-mirror"].append(f"{amod}.{nm}:{msym}")
                else:
                    census["P8-mirrors"].append(f"{amod}.{nm}")
    for m in sorted(p8_grandfathered_mods):
        census["P8-grandfathered-module"].append(m)

    # ---- P3 pairing census (no enforcement beyond reporting)
    holds_by_livemod = defaultdict(list)
    for cname, meta in manifest.items():
        if meta and meta.get("kind") in HOLDS_KINDS:
            for m in corpus.reachable_modules(meta["main"]):
                if m in corpus.mod_file and not is_calib_module(m):
                    holds_by_livemod[m].append(cname)
    for (wname, _, _, wlive, _) in witnesses:
        paired = sorted({h for m in wlive for h in holds_by_livemod.get(m, [])})
        census["P3-paired" if paired else "P3-unpaired"].append(wname)

    return violations, census


def selftest():
    """Banner (b): one planted RED per rule arm, plus a green corpus.

    Each scenario writes a tiny .qnt corpus, parses it with the SAME
    `quint parse` the live gate uses (no hand-built IR — the canary
    pins the shape; the self-test rides the real parser), and asserts
    the exact violation set. An arm that cannot fail its fixture is
    dead code and fails the gate HERE, not silently in production."""
    import shutil
    import subprocess
    import tempfile

    if shutil.which("quint") is None:
        fail("self-test needs `quint` on PATH (the derivation provides it)")

    def build(tmp, files):
        models = Path(tmp) / "models"
        ir = Path(tmp) / "ir"
        (models / "calibration").mkdir(parents=True)
        ir.mkdir()
        # Write the WHOLE corpus before parsing any file: `from`-path
        # imports resolve at parse time, and calibration/ sorts before
        # the live files it imports.
        for rel, text in sorted(files.items()):
            p = models / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text)
        for rel in sorted(files):
            out = ir / (rel.replace("/", "__") + ".json")
            r = subprocess.run(
                ["quint", "parse", "--out", str(out), str(models / rel)],
                capture_output=True,
                text=True,
            )
            if r.returncode != 0:
                # `--out` mode swallows diagnostics (and still writes a
                # partial IR file — fail-open by itself); re-run without
                # it to harvest the real error text.
                diag = subprocess.run(
                    ["quint", "parse", str(models / rel)],
                    capture_output=True,
                    text=True,
                )
                fail(f"self-test: quint parse failed on fixture {rel}:\n{diag.stdout}\n{diag.stderr}")
        return Corpus(ir, models)

    def expect(tag, files, manifest, expected_prefixes):
        with tempfile.TemporaryDirectory() as tmp:
            corpus = build(tmp, files)
            violations, census = run_policy(manifest, corpus)
        unmatched = list(expected_prefixes)
        extra = []
        for v in violations:
            for i, pre in enumerate(unmatched):
                if v.startswith(pre):
                    unmatched.pop(i)
                    break
            else:
                extra.append(v)
        if unmatched or extra:
            fail(
                f"self-test[{tag}]: expectation mismatch\n"
                f"  missing: {unmatched}\n  extra: {extra}\n  got: {violations}"
            )
        return census

    live_a = (
        "module liveA {\n  var x: int\n  action init = x' = 0\n"
        "  action step = x' = x + 1\n  val invX = x >= 0\n  val tauto = true\n}\n"
    )
    live_b = (
        "module liveB {\n  var y: int\n  action init = y' = 0\n"
        "  action step = y' = y\n  val invY = y >= 0\n}\n"
    )
    live_l = (
        "// quint-policy-latches: lx, ly\n"
        "module liveL {\n  var lx: int\n  var ly: int\n"
        "  action init = all { lx' = 0, ly' = 0 }\n"
        "  action step = all { lx' = lx + 1, ly' = ly }\n}\n"
    )
    live_w = (
        "module liveW {\n  var v: int\n  action init = v' = 0\n"
        "  action step = any { v' = v + 1, v' = v }\n"
        "  val invV = v >= 0\n  val wviol = v < 0\n}\n"
    )

    files = {
        "live_a.qnt": live_a,
        "live_b.qnt": live_b,
        "live_l.qnt": live_l,
        "live_w.qnt": live_w,
        "calibration/calib_frozen.qnt": (
            "module calibFrozen {\n  var z: int\n  action init = z' = 0\n"
            "  action step = z' = z + 1\n  val w = z > 100\n}\n"
        ),
        # NB: QUALIFIED import (no `.*`) — that is the legal quint shape
        # the def-flip cheat uses: the namespace stays separate so the
        # redeclaration parses, while the IR import edge still gives the
        # calibration "reaches a live module" credit.
        "calibration/calib_shadow.qnt": ('module calibShadow {\n  import liveA from "../live_a"\n  val invX = false\n}\n'),
        "calibration/calib_lw.qnt": ('module calibLW {\n  import liveL.* from "../live_l"\n  action attack = lx\' = 42\n}\n'),
        # bug_281 red: the SAME attack carried by a `run` declaration's
        # inline anonymous action — the pre-fix root set (qualifier ==
        # "action" only) let this shape assign a declared latch unseen.
        "calibration/calib_lwrun.qnt": (
            'module calibLWRun {\n  import liveL.* from "../live_l"\n'
            "  run attackRun = init.then(all { lx' = 42, ly' = ly })\n}\n"
        ),
    }
    manifest = {
        "tautoCheck": {"kind": "holds", "main": "liveA", "invariants": ["tauto"]},
        "untwCheck": {"kind": "holds", "main": "liveB", "invariants": ["invY"]},
        "frozenW": {"kind": "witness", "main": "calibFrozen", "witness": "w"},
        "shadowW": {"kind": "witness", "main": "calibShadow", "witness": "invX"},
        "bogusCheck": {
            "kind": "holds",
            "main": "liveA",
            "invariants": ["invX"],
            "vacuityExempt": {"invX": {"class": "bogus", "reason": "planted"}},
        },
        "holdsW": {
            "kind": "holds",
            "main": "liveW",
            "invariants": ["invV"],
            "vacuityExempt": {"invV": {"class": "boundsOK", "reason": "planted stale exemption"}},
        },
        "witnessW": {"kind": "witness", "main": "liveW", "witness": "wviol"},
        "ghostCheck": {"kind": "holds", "main": "noSuchModule", "invariants": ["x"]},
        "badInvCheck": {"kind": "holds", "main": "liveA", "invariants": ["noSuchInv"]},
    }
    census = expect(
        "arms",
        files,
        manifest,
        [
            "P1 tautoCheck: invariant leaf 'tauto'",
            "P1 untwCheck: invariant leaf 'invY'",
            "P4 untwCheck: var 'liveB.y'",
            "P2 frozenW: calibration main 'calibFrozen' imports NO live model",
            "P2 shadowW: calibration 'calibShadow' shadows live non-action declaration 'invX'",
            "P6 bogusCheck: unknown vacuityExempt class 'bogus'",
            "P1 bogusCheck: invariant leaf 'invX'",
            "P6 bogusCheck: unused vacuityExempt entry 'invX'",
            "P6 holdsW: unused vacuityExempt entry 'invV'",
            "P5 liveL: declared latch 'ly' fails P4",
            "P5 calibLW: calibration declaration non-identity-assigns latch 'liveL.lx'",
            "P5 calibLWRun: calibration declaration non-identity-assigns latch 'liveL.lx'",
            "R0 ghostCheck: main module 'noSuchModule' not found",
            "R0 badInvCheck: invariant 'noSuchInv' does not resolve",
        ],
    )
    if not census.get("P6-unused-exempt"):
        fail("self-test[arms]: P6-unused-exempt census bucket empty")

    # FATAL ambiguity arm (bug_094): two reachable modules declare one
    # name — the resolver must refuse rather than coin-flip. Captured
    # red (pre-fix): the same corpus flipped between `violations: 0`
    # and `violations: 1` across PYTHONHASHSEED values.
    amb_files = {
        "amb_a.qnt": (
            "module ambA {\n  var va: int\n  action init = va' = 0\n"
            "  action step = va' = va + 1\n  val dup = va >= 0\n}\n"
        ),
        "amb_b.qnt": "module ambB {\n  val dup = true\n}\n",
        "amb_main.qnt": (
            'module ambMain {\n  import ambA from "./amb_a"\n  import ambB from "./amb_b"\n  var q: int\n'
            "  action init = q' = 0\n  action step = q' = q + 1\n}\n"
        ),
    }
    amb_manifest = {"ambCheck": {"kind": "holds", "main": "ambMain", "invariants": ["dup"]}}
    with tempfile.TemporaryDirectory() as tmp:
        corpus = build(tmp, amb_files)
        import contextlib
        import io

        captured = io.StringIO()
        try:
            with contextlib.redirect_stderr(captured):
                run_policy(amb_manifest, corpus)
        except SystemExit as e:
            if e.code != 2:
                fail(f"self-test[ambiguity]: expected exit 2, got {e.code}")
            if "ambiguous name 'dup'" not in captured.getvalue():
                fail(f"self-test[ambiguity]: FATAL fired without naming the collision:\n{captured.getvalue()}")
        else:
            fail("self-test[ambiguity]: ambiguous declaration did not FATAL — the seed-flip hole is back (bug_094)")

    # GREEN corpus: twinned invariant, live writer, clean calibration —
    # the repaired arms must not fire on a healthy corpus.
    green_files = {
        "live_w.qnt": live_w,
        "calibration/calib_run.qnt": ('module calibRun {\n  import liveW.* from "../live_w"\n  action go = v\' = v + 1\n}\n'),
    }
    green_manifest = {
        "holdsW": {"kind": "holds", "main": "liveW", "invariants": ["invV"]},
        "witnessW": {"kind": "witness", "main": "liveW", "witness": "wviol"},
        "runW": {"kind": "run", "main": "calibRun"},
    }
    expect("green", green_files, green_manifest, [])

    # P7 planted red (round-6 WO-S8-4): a let-wrapped anonymous
    # `and{...}` bundle wired as a holds invariant — conj_leaves
    # cannot expand it (the operands are applications, not names), so
    # pre-P7 the bundle rode P1 as ONE leaf. P7 must fire; the P1
    # untwinned violation fires alongside (the bundle has no twin —
    # both are true findings on this corpus).
    live_p7 = (
        "module liveP7 {\n  var p: int\n  action init = p' = 0\n"
        "  action step = p' = p + 1\n"
        "  val bundled =\n    val q = p + 1\n    and { q > 0, p >= 0 }\n"
        "  val leafA = p >= 0\n  val leafB = p + 1 > 0\n"
        "  val named = and { leafA, leafB }\n}\n"
    )
    p7_files = {"live_p7.qnt": live_p7}
    p7_manifest = {"p7Check": {"kind": "holds", "main": "liveP7", "invariants": ["bundled"]}}
    census = expect(
        "p7-red",
        p7_files,
        p7_manifest,
        [
            "P7 p7Check: invariant leaf 'bundled' (liveP7) is an unexpandable conjunction bundle (2 anonymous, let-wrapped)",
            "P1 p7Check: invariant leaf 'bundled'",
        ],
    )
    if not census.get("P7-anonymous-bundle"):
        fail("self-test[p7-red]: P7-anonymous-bundle census bucket empty")

    # P7 planted reds for the engine-complement axes (merged_bug_090 —
    # both TRUE reds against the old anon>=2-after-let-unwrap gate):
    # (a) a MIXED bundle (one anonymous + one named operand, anon=1):
    # the engine refuses it (not all-name), so it shipped as ONE
    # opaque leaf earning intersection-based twin credit over the
    # merged read-set — while the old gate, counting anon>=2, stayed
    # silent. The unified predicate fires on the refusal itself.
    p7_mixed = (
        "module liveP7m {\n  var p: int\n  action init = p' = 0\n"
        "  action step = p' = p + 1\n"
        "  val leafA = p >= 0\n"
        "  val mixed = and { leafA, p < 10 }\n}\n"
    )
    expect(
        "p7-mixed-red",
        {"live_p7m.qnt": p7_mixed},
        {"p7Mixed": {"kind": "holds", "main": "liveP7m", "invariants": ["mixed"]}},
        [
            "P7 p7Mixed: invariant leaf 'mixed' (liveP7m) is an unexpandable conjunction bundle (1 anonymous, 1 named)",
            "P1 p7Mixed: invariant leaf 'mixed'",
        ],
    )
    # (b) a LET-WRAPPED ALL-NAME bundle (anon=0 after unwrap): the
    # engine never unwraps let, so the conjunction shipped opaque —
    # the old gate's own docstring called this exactly the banned
    # shape, and counted 0. The refusal predicate names the wrapper.
    p7_letnamed = (
        "module liveP7l {\n  var p: int\n  action init = p' = 0\n"
        "  action step = p' = p + 1\n"
        "  val leafA = p >= 0\n  val leafB = p + 1 > 0\n"
        "  val letNamed =\n    val unused = 1\n    and { leafA, leafB }\n}\n"
    )
    expect(
        "p7-letnamed-red",
        {"live_p7l.qnt": p7_letnamed},
        {"p7Let": {"kind": "holds", "main": "liveP7l", "invariants": ["letNamed"]}},
        [
            "P7 p7Let: invariant leaf 'letNamed' (liveP7l) is an unexpandable conjunction bundle (2 named, let-wrapped)",
            "P1 p7Let: invariant leaf 'letNamed'",
        ],
    )

    # P7 green: the SAME propositions as NAMED leaves — conj_leaves
    # expands the all-name `and`, each leaf is a plain application
    # (anon count 0), and a live-importing twin earns P1 credit for
    # both leaves. The split is the repair P7 demands.
    p7_green_files = {
        "live_p7.qnt": live_p7,
        "calibration/calib_p7.qnt": ('module calibP7 {\n  import liveP7.* from "../live_p7"\n}\n'),
    }
    p7_green_manifest = {
        "namedCheck": {"kind": "holds", "main": "liveP7", "invariants": ["named"]},
        "p7TwinW": {"kind": "witness", "main": "calibP7", "witness": "leafA"},
    }
    expect("p7-green", p7_green_files, p7_green_manifest, [])

    # P8 planted reds (round-12 WO-S9-9iii): one per arm — the unbound
    # step action, the dead-file mirror, the dead-symbol mirror — plus
    # the green corpus (resolving Mirrors + Environment) and the
    # grandfather census lane. Each runs the same engine the live gate
    # runs, with a real staged mirrors root.
    def expect_p8(tag, files, manifest, mirrors_files, expected_prefixes, grandfather=frozenset()):
        global P8_GRANDFATHER
        saved = P8_GRANDFATHER
        P8_GRANDFATHER = grandfather
        try:
            with tempfile.TemporaryDirectory() as tmp:
                corpus = build(tmp, files)
                models = Path(tmp) / "models"
                mirrors = Path(tmp) / "mirrors"
                for rel, text in mirrors_files.items():
                    fp = mirrors / rel
                    fp.parent.mkdir(parents=True, exist_ok=True)
                    fp.write_text(text)
                violations, census = run_policy(
                    manifest, corpus, models_dir=models, mirrors_root=mirrors
                )
        finally:
            P8_GRANDFATHER = saved
        unmatched = list(expected_prefixes)
        extra = []
        for v in violations:
            for i, pre in enumerate(unmatched):
                if v.startswith(pre):
                    unmatched.pop(i)
                    break
            else:
                extra.append(v)
        if unmatched or extra:
            fail(
                f"self-test[{tag}]: expectation mismatch\n"
                f"  missing: {unmatched}\n  extra: {extra}\n  got: {violations}"
            )
        return census

    p8_live = (
        "module liveP8 {\n  var x: int\n  action init = x' = 0\n"
        "  action unbound = x' = x + 1\n"
        "  // Mirrors: rio-x/src/dead_file.rs:some_fn\n"
        "  action deadFile = x' = x + 1\n"
        "  // Mirrors: rio-x/src/lib.rs:ghost_symbol\n"
        "  action deadSymbol = x' = x + 1\n"
        "  // Mirrors: rio-x/src/lib.rs:real_fn\n"
        "  action mirrored = x' = x + 1\n"
        "  // Environment: the world's move (planted)\n"
        "  action env = x' = x\n"
        "  action step = any { unbound, deadFile, deadSymbol, mirrored, env }\n"
        "  val invX = x >= 0\n}\n"
    )
    p8_files = {"live_p8.qnt": p8_live}
    p8_manifest = {
        "p8Holds": {"kind": "holds", "main": "liveP8", "invariants": ["invX"]},
    }
    p8_mirrors = {"rio-x/src/lib.rs": "pub fn real_fn() {}\n"}
    census = expect_p8(
        "p8-arms",
        p8_files,
        p8_manifest,
        p8_mirrors,
        [
            "P8 p8Holds: step action 'unbound' (liveP8) carries no binding",
            "P8 p8Holds: action 'deadFile' (liveP8) mirrors 'rio-x/src/dead_file.rs:some_fn' but the file does not resolve",
            "P8 p8Holds: action 'deadSymbol' (liveP8) mirrors 'rio-x/src/lib.rs:ghost_symbol' but the symbol is absent",
            # the P1/P4 arms fire on this corpus too (no twin, no
            # writer for the untwinned leaf is not at issue here) —
            # match them so the P8 assertions stay exact:
            "P1 p8Holds: invariant leaf 'invX'",
        ],
    )
    if not census.get("P8-mirrors") or not census.get("P8-environment"):
        fail("self-test[p8-arms]: the resolving Mirrors / Environment census lanes are empty")

    # P8 green: every step action bound and resolvable.
    p8_green = (
        "module liveP8g {\n  var y: int\n  action init = y' = 0\n"
        "  // Mirrors: rio-x/src/lib.rs:real_fn\n"
        "  action a = y' = y + 1\n"
        "  // Environment: frame (planted)\n"
        "  action b = y' = y\n"
        "  action step = any { a, b }\n  val invY = y >= 0\n}\n"
        "module liveP8gTwin {\n  import liveP8g.* from \"./live_p8g\"\n  val w = y < 0\n}\n"
    )
    expect_p8(
        "p8-green",
        {"live_p8g.qnt": p8_green},
        {
            "p8gHolds": {"kind": "holds", "main": "liveP8g", "invariants": ["invY"]},
            "p8gTwin": {"kind": "witness", "main": "liveP8gTwin", "witness": "w"},
        },
        p8_mirrors,
        [],
    )

    # P8 grandfather: the module's whole alphabet is censused, never
    # red — and the census names the module for the burn-down.
    census = expect_p8(
        "p8-grandfather",
        p8_files,
        p8_manifest,
        p8_mirrors,
        ["P1 p8Holds: invariant leaf 'invX'"],
        grandfather=frozenset({"liveP8"}),
    )
    if census.get("P8-grandfathered-module") != ["liveP8"]:
        fail("self-test[p8-grandfather]: grandfathered module not censused")

    # P7 grandfather mechanism: a frozen generator-output entry lands
    # in the census bucket, never the violation list (P1 still fires —
    # grandfathering P7 does not absolve the twin debt).
    global P7_GRANDFATHER
    saved_p7 = P7_GRANDFATHER
    P7_GRANDFATHER = frozenset({("liveP7", "bundled")})
    try:
        census = expect(
            "p7-grandfather",
            p7_files,
            p7_manifest,
            ["P1 p7Check: invariant leaf 'bundled'"],
        )
        if not census.get("P7-grandfathered"):
            fail("self-test[p7-grandfather]: grandfathered bundle not censused")
    finally:
        P7_GRANDFATHER = saved_p7


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest")
    ap.add_argument("--ir-dir")
    ap.add_argument("--models-dir")
    ap.add_argument("--census-only", action="store_true")
    ap.add_argument(
        "--mirrors-root",
        help="staged repo root the P8 Mirrors bindings resolve against (the (vvvvv) staging)",
    )
    ap.add_argument("--assume-latches", default="", help="module:var,var;module:var — provisional P5 domain for census")
    ap.add_argument(
        "--self-test",
        action="store_true",
        help="drive planted corpora through every rule arm (one red per arm + a green corpus) and exit",
    )
    args = ap.parse_args()

    if args.self_test:
        selftest()
        print("quint-policy: self-test OK — every rule arm demonstrated its red and the green corpus passed")
        return
    if not (args.manifest and args.ir_dir and args.models_dir):
        fail("--manifest/--ir-dir/--models-dir are required outside --self-test")

    ir_dir, models_dir = Path(args.ir_dir), Path(args.models_dir)
    canary(ir_dir)
    manifest = json.loads(Path(args.manifest).read_text())
    corpus = Corpus(ir_dir, models_dir)
    violations, census = run_policy(
        manifest,
        corpus,
        args.assume_latches,
        models_dir=models_dir,
        mirrors_root=Path(args.mirrors_root) if args.mirrors_root else None,
    )

    # ---- census print (P6, the owner burn-down artifact)
    print("== quint-policy census ==")
    for k in sorted(census):
        print(f"  {k}: {len(census[k])}")
        for entry in sorted(census[k]):
            print(f"    - {entry}")
    print(f"== violations: {len(violations)} ==")
    for v in violations:
        print(f"  {v}")

    if violations and not args.census_only:
        sys.exit(1)
    print("quint-policy:", "census-only (advisory)" if args.census_only else "OK")


if __name__ == "__main__":
    main()
