.\" SPDX-FileCopyrightText: 2025 Alyssa Ross <hi@alyssa.is>
.\" SPDX-License-Identifier: CC-BY-SA-4.0
.Dd March 30, 2025
.Dt GORGON-ROLLUP 1
.Os
.Sh NAME
.Nm gorgon-rollup
.Nd merge a prioritised list of commits, skipping conflicts
.Sh SYNOPSIS
.Nm
<
.Ar commits
.Sh DESCRIPTION
.Nm
reads a newline-delimited list of commits in the git repository it is
invoked from on standard input, creates a merge commit from them, then
outputs the hash of the merge commit.
.Pp
Commits are processed in the order given, meaning that if there are
conflicts, commits given earlier in the list will be chosen at the
expense of later commits, even if many later commits could have been
included by excluding a single earlier commit.  This means that
commits should be given in order of the priority they should have for
being included in the rollup.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl q , Fl -quiet
Decrease log verbosity.
Can be given multiple times.
.It Fl v , Fl -verbose
Increase log verbosity.
Can be given multiple times.
.Sh IMPLEMENTATION NOTES
The ideal behavior would be to instead find the largest subset of
commits that can all be merged together, but this
.Dq largest compatible subset
problem is NP-hard.
Given that relatively large lists of commits might be given to roll
up, this was found to be infeasible, and the linear-time in-order
merging strategy was chosen instead.
It is expected that most commits will be mergeable with each other
most of the time, so this approach should produce good enough results,
especially given the commits can be prioritised.
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev EMAIL
Email address to use in author and committer metadata for git commits.
The name will always be set to
.Dq Nm .
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Rs
.%A Andy Auyeung
.%A Ajith Abraham
.%D 6 May, 2004
.%T The Largest Compatible Subset Problem for Phylogenetic Data
.%U https://arxiv.org/abs/cs/0405025
.Re
