//! Regenerate `infra/helm/grafana/configmap.yaml` from dashboard JSONs.
//!
//! The ConfigMap is a kubectl-applyable bundle for Grafana's sidecar
//! loader (`grafana_dashboard: "1"` label). Source JSONs are the edit
//! surface; configmap.yaml is derived.

use std::collections::BTreeMap;

use crate::sh::repo_root;
use anyhow::Result;
use serde::Serialize;

const DASHBOARDS: &[&str] = &[
    "build-overview.json",
    "builder-utilization.json",
    "fetcher-utilization.json",
    "store-health.json",
    "scheduler.json",
];

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ConfigMap {
    api_version: &'static str,
    kind: &'static str,
    metadata: Metadata,
    data: BTreeMap<String, String>,
}

#[derive(Serialize)]
struct Metadata {
    name: &'static str,
    labels: BTreeMap<&'static str, &'static str>,
}

pub fn run() -> Result<()> {
    let dir = repo_root().join("infra/helm/grafana");

    let mut data = BTreeMap::new();
    for f in DASHBOARDS {
        let body = std::fs::read_to_string(dir.join(f))?;
        data.insert(f.to_string(), body);
    }

    let cm = ConfigMap {
        api_version: "v1",
        kind: "ConfigMap",
        metadata: Metadata {
            name: "rio-grafana-dashboards",
            labels: BTreeMap::from([("grafana_dashboard", "1")]),
        },
        data,
    };

    let out = dir.join("configmap.yaml");
    let yaml = format!(
        "# GENERATED by `cargo xtask regen grafana` — edit the .json files, not this\n{}",
        serde_yml::to_string(&cm)?
    );
    std::fs::write(&out, &yaml)?;
    crate::ui::set_message(&format!("{} lines", yaml.lines().count()));
    Ok(())
}
