//! Write `rio-dashboard/src/test-support/admin-methods.json` from
//! `MockAdmin::METHODS`.
//!
//! `MockAdmin::METHODS` is generated by `rio-test-support/build.rs`
//! from `admin.proto` and holds proto-canonical PascalCase RPC names.
//! This converts to connect-es `localName` (lowercase first char ONLY —
//! `TriggerGC` → `triggerGC`, not `triggerGc`) and writes a checked-in
//! JSON list so the dashboard's `admin-mock.ts` has a single "copy this"
//! source when the parity test fails.
//!
//! The parity test (`admin-mock.test.ts`) is already self-enforcing:
//! it iterates `AdminService.method` from the connect-es codegen, so
//! a new RPC fails the test regardless of this JSON. This file is a
//! developer aid — the error says "missing stub for listFoo", and
//! `admin-methods.json` is the list to cross-reference.

use anyhow::Result;

use crate::sh::repo_root;
use crate::ui;
use rio_test_support::grpc::MockAdmin;

pub async fn run() -> Result<()> {
    ui::step("admin-methods.json", || async {
        // connect-es localName: proto method name with ONLY the first
        // char lowercased. `TriggerGC` → `triggerGC`. This matches
        // `Object.keys(AdminService.method)` in the dashboard tests —
        // verified against the existing `adminMock` object in
        // `admin-mock.ts` (`triggerGC`, not `triggerGc`).
        //
        // heck's ToLowerCamelCase would give `triggerGc` (wrong):
        // heck re-normalizes consecutive caps. connect-es doesn't.
        let methods: Vec<String> = MockAdmin::METHODS
            .iter()
            .map(|&proto| {
                let mut chars = proto.chars();
                match chars.next() {
                    Some(first) => first.to_lowercase().chain(chars).collect(),
                    None => String::new(),
                }
            })
            .collect();

        let json = serde_json::to_string_pretty(&methods)?;
        let out = repo_root().join("rio-dashboard/src/test-support/admin-methods.json");
        std::fs::write(&out, format!("{json}\n"))?;
        Ok(())
    })
    .await
}
