.\" SPDX-FileCopyrightText: 2023, 2025 Alyssa Ross <hi@alyssa.is>
.\" SPDX-License-Identifier: CC-BY-SA-4.0
.Dd February 11, 2025
.Dt GORGON-GITHUB-EVENTS 1
.Os
.Sh NAME
.Nm gorgon-github-events
.Nd process new events for a GitHub repository
.Sh SYNOPSIS
.Nm
.Op Fl v q
.Op Fl d Ar domain
.Ar owner/repo
.Ar command...
<
.Ar last_seen_ids
>
.Ar seen_ids
.Sh DESCRIPTION
.Nm
processes new events that have occurred on a GitHub repository since the last time
it was run by running
.Ar command
with the events on standard input, with one JSON event object per line.
It can be run regularly to process all events for a GitHub repository,
without the repository administrator permissions required to register a webhook.
.Pp
.Nm
is optimised for at-least-once delivery of events,
as long as it's run frequently enough that GitHub will still provide all the
events that have been generated since the last run.
(A warning will be logged if events appear to have been missed due to having
been run insufficiently frequently.)
A best effort attempt is made to prevent delivery of duplicate events,
if the list of event IDs written to standard output are provided on
the next invocation's standard input.
Events will only be considered to have been delivered if the invocation of
.Ar command
they were provided to exits 0.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl q , Fl -quiet
Decrease log verbosity.
Can be given multiple times.
.It Fl v , Fl -verbose
Increase log verbosity.
Can be given multiple times.
.It Fl d , Fl -domain
Use a custom domain instead of api.github.com, i.e. for GitHub Enterprise.
.El
.Sh ENVIRONMENT
.Bl -tag -width Ds
.It Ev CREDENTIALS_DIR
A path to a directory containing a file named
.Pa GITHUB_TOKEN ,
from which
.Nm
should read a GitHub API token.
.Pp
If running
.Nm
with
.Xr systemd 1 ,
the
.Cm LoadCredential=
option can be used to set this automatically \(em see
.Xr systemd.exec 5 .
.El
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr gorgon-github-events@.timer 1
