//! After `describe_metrics()`, every spec'd metric name has a `describe_*!`
//! call. Catches the "incremented but never described" class
//! (§3 obs-*-unregistered findings: metrics appear in `/metrics` only on
//! first increment, with no `# HELP` line — Grafana tooltips empty,
//! absence alerts can't distinguish "zero" from "not registered").
//!
//! This does NOT catch "described but never incremented in any code path"
//! — that's dead-metric detection, a grep job not a unit test.
//!
//! # Why a custom recorder and not `PrometheusBuilder::build_recorder()`
//!
//! `PrometheusRecorder::render()` only emits `# HELP` for metrics that
//! have been REGISTERED (touched at least once via `counter!()` etc.).
//! `describe_*!` stores the description in a side map but does not
//! register — so `describe_metrics()` alone produces an empty scrape.
//! The custom recorder below intercepts `describe_*` directly.

use rio_test_support::metrics::DescribedNames;

/// Metric names from observability.md's Store Metrics table.
/// Keep in sync; the tracey rule `r[obs.metric.store]` on
/// `describe_metrics()` is the spec link, this is the enforcement.
const STORE_METRICS: &[&str] = &[
    "rio_store_put_path_total",
    "rio_store_put_path_duration_seconds",
    "rio_store_put_path_bytes_total",
    "rio_store_get_path_bytes_total",
    "rio_store_integrity_failures_total",
    "rio_store_chunks_total",
    "rio_store_chunk_dedup_ratio",
    "rio_store_s3_requests_total",
    "rio_store_chunk_cache_hits_total",
    "rio_store_chunk_cache_misses_total",
    "rio_store_gc_path_resurrected_total",
    "rio_store_hmac_rejected_total",
    "rio_store_hmac_bypass_total",
    "rio_store_s3_deletes_pending",
    "rio_store_s3_deletes_stuck",
    "rio_store_gc_chunk_resurrected_total",
    "rio_store_gc_path_swept_total",
    "rio_store_gc_s3_key_enqueued_total",
];

// r[verify obs.metric.store]
#[test]
fn all_spec_metrics_have_describe_call() {
    let recorder = DescribedNames::default();
    let names = recorder.0.clone();

    // with_local_recorder: describe_*! macros route to `recorder` for
    // the duration of the closure only. No global install → no
    // cross-test contamination, no #[serial] needed.
    metrics::with_local_recorder(&recorder, || {
        rio_store::describe_metrics();
    });

    let described = names.lock().unwrap();
    let missing: Vec<_> = STORE_METRICS
        .iter()
        .filter(|name| !described.iter().any(|d| d == *name))
        .collect();

    assert!(
        missing.is_empty(),
        "spec'd metrics missing from describe_metrics(): {missing:?}\n\
         \n\
         described:\n{described:#?}"
    );
}

/// Emit-side: every `metrics::{counter,gauge,histogram}!("name")`
/// literal in src/ has a `describe_*!` with the same name.
///
/// See rio-scheduler's `all_emitted_metrics_are_described` for full
/// rationale — this is the same check, different crate.
///
/// Store's `describe_metrics()` also contains two pre-register
/// `metrics::gauge!().set(0.0)` calls (s3_deletes_pending/stuck) —
/// the build-script grep picks those up from lib.rs, and they ARE
/// described, so they pass. Not a false positive.
// r[verify obs.metric.store]
#[test]
fn all_emitted_metrics_are_described() {
    let emitted: Vec<&str> = EMITTED_METRICS.lines().filter(|l| !l.is_empty()).collect();

    // Precondition self-check: store has 20 metrics. If the
    // build-script grep returns near-zero, the regex broke.
    assert!(
        emitted.len() >= 15,
        "EMITTED_METRICS has only {} entries — build-script grep likely broke",
        emitted.len()
    );

    let recorder = DescribedNames::default();
    let described = recorder.0.clone();
    metrics::with_local_recorder(&recorder, || {
        rio_store::describe_metrics();
    });
    let described = described.lock().unwrap();

    let undescribed: Vec<_> = emitted
        .iter()
        .filter(|name| !described.iter().any(|d| d == **name))
        .collect();

    assert!(
        undescribed.is_empty(),
        "metrics emitted in src/ but NOT in describe_metrics():\n  {undescribed:#?}\n\
         \n\
         Add describe_counter!/describe_gauge!/describe_histogram! to \
         rio-store/src/lib.rs::describe_metrics() AND a row to \
         docs/src/observability.md."
    );
}

// Generated by build.rs — grep of `metrics::{counter,gauge,histogram}!`
// literals across src/. One name per line, sorted, deduplicated.
const EMITTED_METRICS: &str = include_str!(concat!(env!("OUT_DIR"), "/emitted_metrics.txt"));
