//! Minimal [`AdminService`] mock for CLI smoke tests.

use std::net::SocketAddr;

use std::sync::{Arc, RwLock};

use tonic::transport::Server;
use tonic::{Request, Response, Status};

use rio_proto::types;
use rio_proto::{AdminService, AdminServiceServer};

use super::spawn::spawn_grpc_server;

/// Minimal AdminService mock: returns empty-but-valid responses for all
/// unary RPCs. This
/// is for CLI smoke tests that just need "connects + non-error exit",
/// not for asserting on scheduler state (that's what the real
/// AdminServiceImpl tests in rio-scheduler/src/admin/tests.rs are for).
///
/// Streaming RPCs (TriggerGC) return a stream with a
/// single terminal message so the client's drain loop exits cleanly.
// r[impl ts.mock.admin]
#[derive(Clone, Default)]
pub struct MockAdmin {
    /// Every ClearPoison drv_hash received. For asserting the CLI
    /// passed through the positional arg correctly.
    pub clear_poison_calls: Arc<RwLock<Vec<String>>>,
    /// Programmed `GetSpawnIntents` response. Defaults to empty-but-Ok
    /// (a successful zero-intents poll). The nodeclaim-pool
    /// lifecycle-invariants suite sets this between ticks to drive the
    /// reconciler's healthy/⊥ arms (⊥ itself is driven by swapping the
    /// client to a [`super::spawn::dead_channel`], not by this field).
    pub spawn_intents: Arc<RwLock<types::GetSpawnIntentsResponse>>,
    /// Every `AckSpawnedIntents` request received, in order. Lets the
    /// suite assert wire-level effect sets: "no ICE clears sent after
    /// acquire", "no marks for the controller's own reaps".
    pub ack_calls: Arc<RwLock<Vec<types::AckSpawnedIntentsRequest>>>,
    /// Programmed `ListOpenAttempts` response — the open-attempt ledger
    /// view that drives the OA2 wedge tracker's evidence retention.
    pub open_attempts: Arc<RwLock<types::ListOpenAttemptsResponse>>,
    /// Every `ReportAttemptOutcome` request received, in order. Lets
    /// suites assert verdict wire content (reason, intent, the
    /// 124(b) `resubmit_cycle` echo) without a live scheduler.
    pub outcome_calls: Arc<RwLock<Vec<types::ReportAttemptOutcomeRequest>>>,
    /// When set, the next `AckSpawnedIntents` returns UNAVAILABLE
    /// (consumed). Drives the merged_bug_045 commit-on-Ack reds: the
    /// failed Ack is still pushed to `ack_calls` (it reached the wire)
    /// — assert delivery by inspecting which call CARRIED the payload.
    pub fail_next_ack: Arc<std::sync::atomic::AtomicBool>,
    /// When set, the next `AppendInterruptSample` returns UNAVAILABLE
    /// (consumed). Drives the merged_bug_116 counted-drop red.
    pub fail_next_append: Arc<std::sync::atomic::AtomicBool>,
    /// Every `AppendInterruptSample` request received (manual method —
    /// the generated stub would silently default; the node-informer
    /// suites assert sample content and failure accounting).
    pub interrupt_samples: Arc<RwLock<Vec<types::AppendInterruptSampleRequest>>>,
    /// Programmed `MintExecutorTokens` response (bug_121). [`Self::new`]
    /// defaults it to `keyless=true` — the mock signs nothing, so it
    /// truthfully reports the keyless dev posture and token-less
    /// spawns flow exactly as against a keyless scheduler. Program
    /// `tokens` + `keyless=false` to drive the HMAC-mode per-intent
    /// omission arms.
    pub mint_tokens: Arc<RwLock<types::MintExecutorTokensResponse>>,
    /// Every `MintExecutorTokens` request received, in order.
    pub mint_calls: Arc<RwLock<Vec<types::MintExecutorTokensRequest>>>,
}

impl MockAdmin {
    pub fn new() -> Self {
        let mock = Self::default();
        // Truthful default (bug_121 discriminator): the mock holds no
        // HMAC key. Without this, every unprogrammed mint reads as
        // HMAC-mode whole-batch omission and the controller's
        // per-intent fail-closed law spawns nothing.
        mock.mint_tokens.write().unwrap().keyless = true;
        mock
    }
}

// build.rs-generated: defines the `mock_admin_default_methods!` macro
// (expands to default-stub unary method bodies). Must appear BEFORE
// the AdminService impl (macro_rules is textually scoped —
// definition-before-use within a module).
include!(concat!(env!("OUT_DIR"), "/mock_admin_generated.rs"));

#[tonic::async_trait]
impl AdminService for MockAdmin {
    type TriggerGCStream =
        tokio_stream::wrappers::ReceiverStream<Result<types::GcProgress, Status>>;

    // ─── Manual methods: non-default behavior ───────────────────────────
    //
    // These three are NOT generated by build.rs (they're in MANUAL_METHODS
    // there). Streaming RPCs need a non-empty stream body — the CLI drain
    // loop drains to EOF and warns if the terminal frame isn't
    // `is_complete=true`. The two custom unaries record/echo for
    // smoke-test assertions. If you add custom behavior to a
    // currently-generated method, move its proto name into MANUAL_METHODS
    // in build.rs and write the body here.

    async fn trigger_gc(
        &self,
        _: Request<types::GcRequest>,
    ) -> Result<Response<Self::TriggerGCStream>, Status> {
        // Single is_complete=true frame so the CLI's drain loop sees
        // a clean terminal and doesn't emit the "closed without
        // is_complete" warning.
        let (tx, rx) = tokio::sync::mpsc::channel(1);
        let _ = tx
            .send(Ok(types::GcProgress {
                is_complete: true,
                ..Default::default()
            }))
            .await;
        Ok(Response::new(tokio_stream::wrappers::ReceiverStream::new(
            rx,
        )))
    }

    async fn clear_poison(
        &self,
        request: Request<types::ClearPoisonRequest>,
    ) -> Result<Response<types::ClearPoisonResponse>, Status> {
        let req = request.into_inner();
        self.clear_poison_calls
            .write()
            .unwrap()
            .push(req.derivation_hash);
        Ok(Response::new(types::ClearPoisonResponse { cleared: false }))
    }

    async fn create_tenant(
        &self,
        request: Request<types::CreateTenantRequest>,
    ) -> Result<Response<types::CreateTenantResponse>, Status> {
        // Echo back a TenantInfo so the CLI's "returned no TenantInfo"
        // check passes.
        let req = request.into_inner();
        Ok(Response::new(types::CreateTenantResponse {
            tenant: Some(types::TenantInfo {
                tenant_id: "00000000-0000-0000-0000-000000000000".into(),
                tenant_name: req.tenant_name,
                ..Default::default()
            }),
        }))
    }

    async fn get_spawn_intents(
        &self,
        _: Request<types::GetSpawnIntentsRequest>,
    ) -> Result<Response<types::GetSpawnIntentsResponse>, Status> {
        Ok(Response::new(self.spawn_intents.read().unwrap().clone()))
    }

    async fn ack_spawned_intents(
        &self,
        request: Request<types::AckSpawnedIntentsRequest>,
    ) -> Result<Response<()>, Status> {
        self.ack_calls.write().unwrap().push(request.into_inner());
        if self
            .fail_next_ack
            .swap(false, std::sync::atomic::Ordering::SeqCst)
        {
            return Err(Status::unavailable("programmed ack failure"));
        }
        Ok(Response::new(()))
    }

    async fn report_attempt_outcome(
        &self,
        request: Request<types::ReportAttemptOutcomeRequest>,
    ) -> Result<Response<types::ReportAttemptOutcomeResponse>, Status> {
        self.outcome_calls
            .write()
            .unwrap()
            .push(request.into_inner());
        Ok(Response::new(types::ReportAttemptOutcomeResponse::default()))
    }

    async fn list_open_attempts(
        &self,
        _: Request<types::ListOpenAttemptsRequest>,
    ) -> Result<Response<types::ListOpenAttemptsResponse>, Status> {
        Ok(Response::new(self.open_attempts.read().unwrap().clone()))
    }

    async fn mint_executor_tokens(
        &self,
        request: Request<types::MintExecutorTokensRequest>,
    ) -> Result<Response<types::MintExecutorTokensResponse>, Status> {
        self.mint_calls.write().unwrap().push(request.into_inner());
        Ok(Response::new(self.mint_tokens.read().unwrap().clone()))
    }

    async fn append_interrupt_sample(
        &self,
        request: Request<types::AppendInterruptSampleRequest>,
    ) -> Result<Response<()>, Status> {
        self.interrupt_samples
            .write()
            .unwrap()
            .push(request.into_inner());
        if self
            .fail_next_append
            .swap(false, std::sync::atomic::Ordering::SeqCst)
        {
            return Err(Status::unavailable("programmed append failure"));
        }
        Ok(Response::new(()))
    }

    // ─── Generated methods: Default::default() stubs ────────────────────
    //
    // One async fn per unary RPC NOT in MANUAL_METHODS, each returning
    // Ok(Response::new(<T>::default())). Generated by build.rs from
    // admin.proto so adding a new unary RPC requires zero Rust changes.
    // See build.rs's doc comment for the full story.
    mock_admin_default_methods!();
}

/// Spawn a MockAdmin on an ephemeral port. Returns `(admin, addr, handle)`.
///
/// Plaintext — no TLS. For rio-cli smoke tests: run with no
///
pub async fn spawn_mock_admin()
-> anyhow::Result<(MockAdmin, SocketAddr, tokio::task::JoinHandle<()>)> {
    let admin = MockAdmin::new();
    let router = Server::builder().add_service(AdminServiceServer::new(admin.clone()));
    let (addr, handle) = spawn_grpc_server(router).await;
    Ok((admin, addr, handle))
}
