# Per-member and workspace filesets — the source-tree slices that
# every build/check/coverage derivation reads. Single source of truth
# for "which files reach the sandbox" so adding a crate or moving a
# directory is a one-place change.
#
# Extracted from flake.nix's perSystem `let` block. All paths are
# rebased onto `unfilteredRoot` (the workspace root passed in) — `./X`
# literals here would resolve to nix/lib/, not the repo root.
{
  lib,
  # Cargo.toml [workspace] members — adding/removing a crate is a
  # Cargo.toml-only change; everything below is derived.
  members,
  # Workspace root path (`./.` from flake.nix).
  unfilteredRoot,
  # Drops workspace-hack from per-member maps. Defined in flake.nix so
  # nix/checks.nix shares the same filter — single definition.
  noHack,
}:
rec {
  # Per-member filesets — the FULL crate subtree, including
  # tests/ and proptest-regressions/. This is what test-time
  # builds (nextest, clippy --all-targets, coverage) and the
  # nextest runtime overlay consume. No commonCargoSources
  # filter — that strips proto/, which rio-proto's build.rs
  # needs as ./proto/.
  #
  # After the cross-directory-read elimination, every crate's
  # fileset is just its own directory — no per-crate unions
  # or exclusions. The lib/bin vs. test split is layered on
  # top in memberBinFilesets below, not encoded here.
  memberFilesets = lib.genAttrs members (n: unfilteredRoot + "/${n}");

  # Per-member fileset for the lib/bin compile — memberFilesets
  # MINUS tests/ and proptest-regressions/. buildRustCrate never
  # reads tests/ when buildTests=false (the entire `find tests/`
  # step is gated on it; proptest replays at TEST RUNTIME, not
  # compile time), so a tests/-only edit must not rehash the
  # binary derivations that VM tests, docker images, crdgen, and
  # the lib-only clippy/doc checks consume.
  #
  # nix/checks.nix's mkTestVariant overrides `src` back to the
  # wide variant for buildTests=true builds — without that, the
  # `find tests/` at build time discovers zero integration test
  # binaries and nextest silently runs nothing.
  memberBinFilesets = lib.mapAttrs (
    name: fs:
    lib.fileset.difference fs (
      lib.fileset.unions [
        (lib.fileset.maybeMissing (unfilteredRoot + "/${name}/tests"))
        (lib.fileset.maybeMissing (unfilteredRoot + "/${name}/proptest-regressions"))
      ]
    )
  ) memberFilesets;

  # lcov --extract patterns: one per workspace member
  # (`<crateName>/*` after crate2nix.nix's localRemap), so
  # coverage for non-rio-prefixed members (xtask) isn't
  # silently dropped by a `'rio-*'` literal. Threaded into
  # checks.nix (covLcovs) and coverage.nix (mkPerTestLcov).
  covExtractPatterns = lib.mapAttrsToList (n: _: "${n}/*") (noHack memberFilesets);

  # Union for consumers that still need the whole workspace as
  # one tree (nextest CARGO_MANIFEST_DIR, deny, fuzz, genhtml).
  workspaceFileset = lib.fileset.unions (
    builtins.attrValues memberFilesets
    ++ [
      (unfilteredRoot + "/Cargo.toml")
      (unfilteredRoot + "/Cargo.lock")
      # sqlx offline query cache — content-addressed JSON per
      # query!(...) callsite. Generated by `cargo xtask regen
      # sqlx`. Required at compile time when SQLX_OFFLINE=1 so
      # the macro doesn't try to connect to PG during the
      # crate2nix build. The cache is COMMITTED (a fresh clone has
      # it); maybeMissing keeps eval green in the only reachable
      # no-.sqlx states — `rm -rf .sqlx` recovery and mid-regen
      # swaps — so the failure surfaces at compile with sqlx's own
      # diagnostic instead of at eval.
      (lib.fileset.maybeMissing (unfilteredRoot + "/.sqlx"))
      # Seccomp profile JSON (embedded via include_str! in
      # rio-controller tests — build-time presence check so a
      # missing profile fails compile, not silently at deploy).
      (unfilteredRoot + "/nix/nixos-node/seccomp")
    ]
  );
  workspaceSrc = lib.fileset.toSource {
    root = unfilteredRoot;
    fileset = workspaceFileset;
  };

  # Per-crate src isolation for crate2nix: build-from-json.nix
  # resolves local crate srcs as `workspaceSrc + "/<path>"` — a
  # subpath of ONE store hash. Editing rio-cli rehashes
  # workspaceSrc → invalidates every member. Precompute a
  # per-member `lib.fileset.toSource` rooted at the crate dir;
  # crate2nix.nix intercepts `crate_.src` at
  # buildRustCrateForPkgs. buildRustCrate's unpack copies the
  # store path to $NIX_BUILD_TOP and `workspace_member` defaults
  # to "." (Cargo.toml at root), so a crate-root-shaped src
  # works without sourceRoot games.
  #
  # Derived from memberBinFilesets (NOT memberFilesets) so the
  # base build derivations are hash-stable across tests/-only
  # edits. This is the input to crateBuild/crateBuildCov/fuzz —
  # everything downstream of those (workspaceBins → VM tests,
  # memberBins → docker, clippyMember, docMember) inherits the
  # narrow src and stays cached when only test code changes.
  memberSrcs = lib.mapAttrs (
    name: fileset:
    lib.fileset.toSource {
      root = unfilteredRoot + "/${name}";
      inherit fileset;
    }
  ) memberBinFilesets;

  # Manifests + lockfile only — NO `.rs` source content. The
  # minimal fileset `cargo metadata` needs to resolve workspace
  # structure and the dep graph. Pair with `stubTargetFiles` so
  # cargo's autotest/autobin discovery finds the (empty) target
  # files. Shared by cargoMetadataJson (nix/lib/nextest-args.nix
  # → nix/checks.nix), the deny check (nix/misc-checks.nix), and
  # mutants-smoke (nix/mutants.nix) — all manifest-only checks
  # that should not rebuild on every `.rs` edit.
  manifestsFileset = lib.fileset.unions [
    (unfilteredRoot + "/Cargo.toml")
    (unfilteredRoot + "/Cargo.lock")
    (lib.fileset.fileFilter (f: f.name == "Cargo.toml") unfilteredRoot)
  ];

  # Mirror cargo's auto-detected target files (src/lib.rs,
  # src/main.rs, src/bin/*.rs, tests/*.rs, tests/*/main.rs)
  # as empty stubs. pathExists/readDir at eval time depend
  # on file EXISTENCE not content, so editing the bodies
  # doesn't change this string — manifest-only checks stay
  # cached until a target file is added or removed.
  stubTargetFiles =
    let
      stubIf =
        p:
        lib.optionalString (builtins.pathExists p) ''
          mkdir -p "$(dirname ${lib.removePrefix (toString unfilteredRoot + "/") (toString p)})"
          touch ${lib.removePrefix (toString unfilteredRoot + "/") (toString p)}
        '';
      stubBinDir =
        d:
        lib.optionalString (builtins.pathExists d) (
          lib.concatMapStrings (f: stubIf (d + "/${f}")) (builtins.attrNames (builtins.readDir d))
        );
      # Mirrors cargo's integration-test autodiscovery:
      #   tests/<name>.rs       → target `<name>`
      #   tests/<name>/main.rs  → target `<name>`
      # Other files in tests/ (mod.rs, helpers, fixtures)
      # are NOT autotest targets — cargo only compiles them
      # when a target `mod`-includes them, which the metadata
      # walk never does.
      stubTestDir =
        d:
        lib.optionalString (builtins.pathExists d) (
          let
            entries = builtins.readDir d;
          in
          lib.concatMapStrings (
            f:
            if entries.${f} == "regular" && lib.hasSuffix ".rs" f then
              stubIf (d + "/${f}")
            else if entries.${f} == "directory" then
              stubIf (d + "/${f}/main.rs")
            else
              ""
          ) (builtins.attrNames entries)
        );
    in
    lib.concatMapStrings (
      m:
      stubIf (unfilteredRoot + "/${m}/src/lib.rs")
      + stubIf (unfilteredRoot + "/${m}/src/main.rs")
      + stubBinDir (unfilteredRoot + "/${m}/src/bin")
      + stubTestDir (unfilteredRoot + "/${m}/tests")
    ) (builtins.attrNames memberFilesets);
}
