# Per-member and workspace filesets — the source-tree slices that
# every build/check/coverage derivation reads. Single source of truth
# for "which files reach the sandbox" so adding a crate or moving a
# directory is a one-place change.
#
# Extracted from flake.nix's perSystem `let` block. All paths are
# rebased onto `unfilteredRoot` (the workspace root passed in) — `./X`
# literals here would resolve to nix/lib/, not the repo root.
{
  lib,
  # Cargo.toml [workspace] members — adding/removing a crate is a
  # Cargo.toml-only change; everything below is derived.
  members,
  # Workspace root path (`./.` from flake.nix).
  unfilteredRoot,
  # Drops workspace-hack from per-member maps. Defined in flake.nix so
  # nix/checks.nix shares the same filter — single definition.
  noHack,
}:
rec {
  # Per-member filesets — the FULL crate subtree, including
  # tests/ and proptest-regressions/. This is what test-time
  # builds (nextest, clippy --all-targets, coverage) and the
  # nextest runtime overlay consume. No commonCargoSources
  # filter — that strips proto/, which rio-proto's build.rs
  # needs as ./proto/.
  #
  # After the cross-directory-read elimination, every crate's
  # fileset is just its own directory — no per-crate unions
  # or exclusions. The lib/bin vs. test split is layered on
  # top in memberBinFilesets below, not encoded here.
  memberFilesets = lib.genAttrs members (n: unfilteredRoot + "/${n}");

  # Per-member fileset for the lib/bin compile — memberFilesets
  # MINUS tests/ and proptest-regressions/. buildRustCrate never
  # reads tests/ when buildTests=false (the entire `find tests/`
  # step is gated on it; proptest replays at TEST RUNTIME, not
  # compile time), so a tests/-only edit must not rehash the
  # binary derivations that VM tests, docker images, crdgen, and
  # the lib-only clippy/doc checks consume.
  #
  # nix/checks.nix's mkTestVariant overrides `src` back to the
  # wide variant for buildTests=true builds — without that, the
  # `find tests/` at build time discovers zero integration test
  # binaries and nextest silently runs nothing.
  memberBinFilesets = lib.mapAttrs (
    name: fs:
    lib.fileset.difference fs (
      lib.fileset.unions [
        (lib.fileset.maybeMissing (unfilteredRoot + "/${name}/tests"))
        (lib.fileset.maybeMissing (unfilteredRoot + "/${name}/proptest-regressions"))
      ]
    )
  ) memberFilesets;

  # lcov --extract patterns: one per workspace member
  # (`<crateName>/*` after crate2nix.nix's localRemap), so
  # coverage for non-rio-prefixed members (xtask) isn't
  # silently dropped by a `'rio-*'` literal. Threaded into
  # checks.nix (covLcovs) and coverage.nix (mkPerTestLcov).
  covExtractPatterns = lib.mapAttrsToList (n: _: "${n}/*") (noHack memberFilesets);

  # Union for consumers that still need the whole workspace as
  # one tree (nextest CARGO_MANIFEST_DIR, deny, fuzz, genhtml).
  workspaceFileset = lib.fileset.unions (
    builtins.attrValues memberFilesets
    ++ [
      (unfilteredRoot + "/Cargo.toml")
      (unfilteredRoot + "/Cargo.lock")
      # sqlx offline query cache — content-addressed JSON per
      # query!(...) callsite. Generated by `cargo xtask regen
      # sqlx`. Required at compile time when SQLX_OFFLINE=1 so
      # the macro doesn't try to connect to PG during the
      # crate2nix build. maybeMissing: a fresh clone before the
      # first `cargo xtask regen sqlx` won't have .sqlx/ yet.
      (lib.fileset.maybeMissing (unfilteredRoot + "/.sqlx"))
      # Seccomp profile JSON (embedded via include_str! in
      # rio-controller tests — build-time presence check so a
      # missing profile fails compile, not silently at deploy).
      (unfilteredRoot + "/nix/nixos-node/seccomp")
    ]
  );
  workspaceSrc = lib.fileset.toSource {
    root = unfilteredRoot;
    fileset = workspaceFileset;
  };

  # Per-crate src isolation for crate2nix: build-from-json.nix
  # resolves local crate srcs as `workspaceSrc + "/<path>"` — a
  # subpath of ONE store hash. Editing rio-cli rehashes
  # workspaceSrc → invalidates every member. Precompute a
  # per-member `lib.fileset.toSource` rooted at the crate dir;
  # crate2nix.nix intercepts `crate_.src` at
  # buildRustCrateForPkgs. buildRustCrate's unpack copies the
  # store path to $NIX_BUILD_TOP and `workspace_member` defaults
  # to "." (Cargo.toml at root), so a crate-root-shaped src
  # works without sourceRoot games.
  #
  # Derived from memberBinFilesets (NOT memberFilesets) so the
  # base build derivations are hash-stable across tests/-only
  # edits. This is the input to crateBuild/crateBuildCov/fuzz —
  # everything downstream of those (workspaceBins → VM tests,
  # memberBins → docker, clippyMember, docMember) inherits the
  # narrow src and stays cached when only test code changes.
  memberSrcs = lib.mapAttrs (
    name: fileset:
    lib.fileset.toSource {
      root = unfilteredRoot + "/${name}";
      inherit fileset;
    }
  ) memberBinFilesets;
}
