# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023 Alyssa Ross <hi@alyssa.is>

[licenses]
allow = [
    "EUPL-1.2",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-DFS-2016",
]
copyleft = "warn"
allow-osi-fsf-free = "both"

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
