version = 1
SPDX-PackageName = "gorgon"
SPDX-PackageSupplier = ["Alyssa Ross <hi@alyssa.is>", "embr <git@liclac.eu>"]
SPDX-PackageDownloadLocation = "https://codeberg.org/gorgon/gorgon"

[[annotations]]
path = "vendor/bootstrap/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2011-2023 The Bootstrap Authors"
SPDX-License-Identifier = "MIT"
