//! Prior cluster signing keys (`cluster_key_history` table, migration 027).
//!
//! One query: load all unretired prior-cluster pubkey entries for the
//! sig-visibility gate. Called once at startup (main.rs); the returned
//! `Vec<String>` goes into `TenantSigner::with_prior_cluster`.
//!
//! Insert/retire are admin-CLI territory (rotation is a human-driven
//! operation, not hot-path).

use super::MetadataError;
use sqlx::PgPool;

// r[impl store.key.rotation-cluster-history]
/// Load prior cluster public keys still within their grace period.
///
/// Returns `name:base64(pubkey)` strings — what `Signer::trusted_key_entry`
/// writes during rotation. Each is ready for direct push into
/// `sig_visibility_gate`'s trusted set (`any_sig_trusted` parses this
/// format).
///
/// `WHERE retired_at IS NULL` — retired rows are audit-only, not
/// trusted. An operator ends the grace period by setting `retired_at`,
/// not by deleting the row.
///
/// Ordered by `created_at DESC` so the most recently rotated-out key
/// (most likely to have live sigs) is first in the verify loop. Minor
/// optimization — `any_sig_trusted` is O(keys×sigs) regardless, but
/// early-exit on common case is free.
pub async fn load_cluster_key_history(pool: &PgPool) -> Result<Vec<String>, MetadataError> {
    let rows: Vec<(String,)> = sqlx::query_as(
        "SELECT pubkey FROM cluster_key_history \
         WHERE retired_at IS NULL \
         ORDER BY created_at DESC",
    )
    .fetch_all(pool)
    .await?;

    Ok(rows.into_iter().map(|(pk,)| pk).collect())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::signing::{Signer, TenantSigner};
    use rio_test_support::TestDb;
    use tracing_test::traced_test;

    #[tokio::test]
    async fn empty_history_is_empty_vec() {
        let db = TestDb::new(&crate::MIGRATOR).await;
        let keys = load_cluster_key_history(&db.pool).await.unwrap();
        assert!(keys.is_empty(), "fresh DB → no prior keys");
    }

    #[tokio::test]
    async fn retired_keys_excluded() {
        let db = TestDb::new(&crate::MIGRATOR).await;

        sqlx::query(
            "INSERT INTO cluster_key_history (pubkey, retired_at) VALUES \
             ('active-key:aaaa', NULL), \
             ('retired-key:bbbb', now())",
        )
        .execute(&db.pool)
        .await
        .unwrap();

        let keys = load_cluster_key_history(&db.pool).await.unwrap();
        assert_eq!(keys, vec!["active-key:aaaa".to_string()]);
    }

    #[tokio::test]
    async fn ordered_newest_first() {
        let db = TestDb::new(&crate::MIGRATOR).await;

        // Insert with explicit timestamps so ordering is deterministic
        // regardless of insert speed.
        sqlx::query(
            "INSERT INTO cluster_key_history (pubkey, created_at) VALUES \
             ('old:a', '2026-01-01T00:00:00Z'), \
             ('new:b', '2026-02-01T00:00:00Z')",
        )
        .execute(&db.pool)
        .await
        .unwrap();

        let keys = load_cluster_key_history(&db.pool).await.unwrap();
        assert_eq!(keys, vec!["new:b".to_string(), "old:a".to_string()]);
    }

    // r[verify store.key.rotation-cluster-history]
    /// Malformed `cluster_key_history.pubkey` entries are warn+skipped at
    /// `TenantSigner::load_prior_cluster`, not silently dropped in
    /// `any_sig_trusted`. Operator typo → loud warn with reason, not
    /// "old-key paths go dark with zero signal".
    ///
    /// This is the mutation-catch for the T1 validation loop: change the
    /// `Err(reason) => warn!` arm back to silent `Err(_) => {}` and the
    /// `logs_contain` asserts below FAIL.
    #[tokio::test]
    #[traced_test]
    async fn load_prior_cluster_skips_malformed_warns_loudly() {
        let db = TestDb::new(&crate::MIGRATOR).await;

        // Valid entries generated by the same code path operators use
        // during rotation (Signer::trusted_key_entry). Not hardcoded b64
        // that might drift from ed25519-dalek's accepted-point set.
        let v1 = Signer::from_seed("cache-v1", &[0xAA; 32]).trusted_key_entry();
        let v2 = Signer::from_seed("cache-v2", &[0xBB; 32]).trusted_key_entry();

        // 3 entries: valid, malformed (bad b64 — operator typo), valid.
        sqlx::query(
            "INSERT INTO cluster_key_history (pubkey, created_at) VALUES \
             ($1, '2026-01-01T00:00:00Z'), \
             ('cache-bad:!!!not base64!!!', '2026-01-02T00:00:00Z'), \
             ($2, '2026-01-03T00:00:00Z')",
        )
        .bind(&v1)
        .bind(&v2)
        .execute(&db.pool)
        .await
        .unwrap();

        let loaded = TenantSigner::load_prior_cluster(&db.pool).await.unwrap();

        // Malformed entry skipped; both valid entries loaded.
        assert_eq!(loaded.len(), 2, "malformed entry skipped, 2 valid loaded");
        assert!(
            loaded.iter().any(|e| e.starts_with("cache-v1:")),
            "cache-v1 loaded"
        );
        assert!(
            loaded.iter().any(|e| e.starts_with("cache-v2:")),
            "cache-v2 loaded"
        );
        assert!(
            !loaded.iter().any(|e| e.starts_with("cache-bad:")),
            "cache-bad skipped"
        );

        // The warn is LOUD: names the table, action taken, what to do.
        assert!(
            logs_contain("malformed cluster_key_history entry"),
            "per-entry warn fired"
        );
        assert!(
            logs_contain("pubkey is not valid base64"),
            "warn includes the specific reason"
        );
        assert!(
            logs_contain("cache-bad:"),
            "warn includes the offending entry"
        );
        // Summary warn — the one-line "check your logs" signal.
        assert!(logs_contain("some entries malformed"), "summary warn fired");
        assert!(logs_contain("skipped=1"), "summary warn has the count");
    }

    /// All-valid history → no warn noise. Clean path stays clean.
    #[tokio::test]
    #[traced_test]
    async fn load_prior_cluster_all_valid_no_warn() {
        let db = TestDb::new(&crate::MIGRATOR).await;

        let v1 = Signer::from_seed("clean-v1", &[0xCC; 32]).trusted_key_entry();
        sqlx::query("INSERT INTO cluster_key_history (pubkey) VALUES ($1)")
            .bind(&v1)
            .execute(&db.pool)
            .await
            .unwrap();

        let loaded = TenantSigner::load_prior_cluster(&db.pool).await.unwrap();

        assert_eq!(loaded.len(), 1);
        assert!(
            !logs_contain("malformed"),
            "no malformed entries → no warn noise"
        );
    }
}
