# SPDX-FileCopyrightText: 2024 embr <git@liclac.eu>
#
# SPDX-License-Identifier: EUPL-1.2

depends_on:
- lint
- build

matrix:
  # Remember to update this when bumping nixpkgs:
  # $ nix-instantiate --json --eval --expr 'let pkgs = (import nix/nixpkgs.default.nix); in with pkgs.lib; filter (hasInfix "_") (attrNames (pkgs.callPackage ./nix/nix-packages.nix {}))'
  NIX_ATTR: ["lix_2_90", "lix_2_91", "nix_2_24", "nix_2_25"]

steps:
- name: test nix-supervisor (${NIX_ATTR})
  image: bash
  commands:
  - test -n "$CI_HACK_WORK_DIR" && cd $CI_HACK_WORK_DIR; true
  - nix-build --no-out-link nix-supervisor/tests.nix -A ${NIX_ATTR}

- name: test nix-daemon (${NIX_ATTR})
  image: bash
  commands:
  - test -n "$CI_HACK_WORK_DIR" && cd $CI_HACK_WORK_DIR; true
  - nix-build --no-out-link nix-daemon/tests.nix -A ${NIX_ATTR}

- name: test nix-web (${NIX_ATTR})
  image: bash
  commands:
  - test -n "$CI_HACK_WORK_DIR" && cd $CI_HACK_WORK_DIR; true
  - nix-build --no-out-link nix-web/tests.nix -A ${NIX_ATTR}

when:
- event: [ push, pull_request, pull_request_closed, tag, release, manual, cron ]
