//! After `describe_metrics()`, every spec'd metric name has a `describe_*!`
//! call. Catches the "incremented but never described" class
//! (§3 obs-*-unregistered findings: metrics appear in `/metrics` only on
//! first increment, with no `# HELP` line — Grafana tooltips empty,
//! absence alerts can't distinguish "zero" from "not registered").
//!
//! This does NOT catch "described but never incremented in any code path"
//! — that's dead-metric detection, a grep job not a unit test.
//!
//! # Why a custom recorder and not `PrometheusBuilder::build_recorder()`
//!
//! `PrometheusRecorder::render()` only emits `# HELP` for metrics that
//! have been REGISTERED (touched at least once via `counter!()` etc.).
//! `describe_*!` stores the description in a side map but does not
//! register — so `describe_metrics()` alone produces an empty scrape.
//! The custom recorder below intercepts `describe_*` directly.

use rio_test_support::metrics::{
    assert_emitted_metrics_described, assert_histograms_have_buckets, assert_spec_metrics_described,
};

/// Metric names from observability.md's Scheduler Metrics table.
/// Keep in sync; the tracey rule `r[obs.metric.scheduler]` on
/// `describe_metrics()` is the spec link, this is the enforcement.
const SCHEDULER_METRICS: &[&str] = &[
    "rio_scheduler_builds_total",
    "rio_scheduler_builds_active",
    "rio_scheduler_derivations_queued",
    "rio_scheduler_derivations_running",
    "rio_scheduler_assignment_latency_seconds",
    "rio_scheduler_build_duration_seconds",
    "rio_scheduler_cache_hits_total",
    "rio_scheduler_cache_check_failures_total",
    "rio_scheduler_queue_backpressure",
    "rio_scheduler_workers_active",
    "rio_scheduler_assignments_total",
    "rio_scheduler_prefetch_hints_sent_total",
    "rio_scheduler_prefetch_paths_sent_total",
    "rio_scheduler_cleanup_dropped_total",
    "rio_scheduler_transition_rejected_total",
    "rio_scheduler_log_lines_forwarded_total",
    "rio_scheduler_log_flush_total",
    "rio_scheduler_log_flush_failures_total",
    "rio_scheduler_log_flush_dropped_total",
    "rio_scheduler_log_forward_dropped_total",
    "rio_scheduler_critical_path_accuracy",
    "rio_scheduler_size_class_assignments_total",
    "rio_scheduler_misclassifications_total",
    "rio_scheduler_class_drift_total",
    "rio_scheduler_cutoff_seconds",
    "rio_scheduler_class_queue_depth",
    "rio_scheduler_cache_check_circuit_open_total",
    "rio_scheduler_event_persist_dropped_total",
    "rio_scheduler_backstop_timeouts_total",
    "rio_scheduler_build_timeouts_total",
    "rio_scheduler_recovery_total",
    "rio_scheduler_recovery_duration_seconds",
    "rio_scheduler_worker_disconnects_total",
    "rio_scheduler_cancel_signals_total",
    "rio_scheduler_lease_acquired_total",
    "rio_scheduler_lease_lost_total",
    "rio_scheduler_estimator_refresh_total",
    "rio_scheduler_build_graph_edges",
];

// Generated by build.rs — grep of `metrics::{counter,gauge,histogram}!`
// literals across src/. One name per line, sorted, deduplicated.
const EMITTED_METRICS: &str = include_str!(concat!(env!("OUT_DIR"), "/emitted_metrics.txt"));

// r[verify obs.metric.scheduler]
#[test]
fn all_spec_metrics_have_describe_call() {
    assert_spec_metrics_described(
        SCHEDULER_METRICS,
        rio_scheduler::describe_metrics,
        "rio-scheduler",
    );
}

// r[verify obs.metric.scheduler]
#[test]
fn all_emitted_metrics_are_described() {
    assert_emitted_metrics_described(
        EMITTED_METRICS,
        30,
        rio_scheduler::describe_metrics,
        "rio-scheduler",
    );
}

// r[verify obs.metric.scheduler]
// Every histogram described by rio_scheduler must have a
// HISTOGRAM_BUCKET_MAP entry (or be in DEFAULT_BUCKETS_OK). The existing
// describe-only test catches "forgot to describe" but NOT "forgot to
// configure buckets" — a histogram with only describe_histogram! and no
// Matcher::Full gets default [0.005..10.0] buckets. For count-type or
// long-duration metrics, every sample lands in +Inf and p99 is unusable.
// This caught rio_scheduler_build_graph_edges (P0321): described, emitted,
// spec'd with suggested buckets — but init_metrics had no Matcher for it.
#[test]
fn all_histograms_have_bucket_config() {
    use rio_common::observability::HISTOGRAM_BUCKET_MAP;

    // Histograms that genuinely fit [0.005..10.0]. See the
    // HISTOGRAM_BUCKET_MAP doc comment for the rationale on each.
    const DEFAULT_BUCKETS_OK: &[&str] = &["rio_scheduler_recovery_duration_seconds"];

    assert_histograms_have_buckets(
        rio_scheduler::describe_metrics,
        HISTOGRAM_BUCKET_MAP,
        DEFAULT_BUCKETS_OK,
        "rio-scheduler",
    );
}
