//! After `describe_metrics()`, every spec'd metric name has a `describe_*!`
//! call. Catches the "incremented but never described" class
//! (§3 obs-*-unregistered findings: metrics appear in `/metrics` only on
//! first increment, with no `# HELP` line — Grafana tooltips empty,
//! absence alerts can't distinguish "zero" from "not registered").
//!
//! This does NOT catch "described but never incremented in any code path"
//! — that's dead-metric detection, a grep job not a unit test.
//!
//! # Why a custom recorder and not `PrometheusBuilder::build_recorder()`
//!
//! `PrometheusRecorder::render()` only emits `# HELP` for metrics that
//! have been REGISTERED (touched at least once via `counter!()` etc.).
//! `describe_*!` stores the description in a side map but does not
//! register — so `describe_metrics()` alone produces an empty scrape.
//! The custom recorder below intercepts `describe_*` directly.

use rio_test_support::metrics::{
    assert_emitted_metrics_described, assert_histograms_have_buckets, assert_spec_metrics_described,
};

/// Metric names from observability.md's Scheduler Metrics table.
/// Derived at build time via build.rs → spec_metrics.txt.
const SPEC_METRICS_RAW: &str = include_str!(concat!(env!("OUT_DIR"), "/spec_metrics.txt"));

// Generated by build.rs — grep of `metrics::{counter,gauge,histogram}!`
// literals across src/. One name per line, sorted, deduplicated.
const EMITTED_METRICS: &str = include_str!(concat!(env!("OUT_DIR"), "/emitted_metrics.txt"));

// r[verify obs.metric.scheduler]
#[test]
fn all_spec_metrics_have_describe_call() {
    let spec_metrics: Vec<&str> = SPEC_METRICS_RAW.lines().filter(|l| !l.is_empty()).collect();
    // Floor-check: obs.md's Scheduler Metrics table has ≥20 rows.
    // Guards against vacuous pass if the grep path breaks.
    assert!(
        spec_metrics.len() >= 20,
        "spec_metrics.txt has only {} entries — build.rs grep broken?",
        spec_metrics.len()
    );
    assert_spec_metrics_described(
        &spec_metrics,
        rio_scheduler::describe_metrics,
        "rio-scheduler",
    );
}

// r[verify obs.metric.scheduler]
#[test]
fn all_emitted_metrics_are_described() {
    assert_emitted_metrics_described(
        EMITTED_METRICS,
        30,
        rio_scheduler::describe_metrics,
        "rio-scheduler",
    );
}

// r[verify obs.metric.scheduler]
// Every histogram described by rio_scheduler must have a
// HISTOGRAM_BUCKET_MAP entry (or be in DEFAULT_BUCKETS_OK). The existing
// describe-only test catches "forgot to describe" but NOT "forgot to
// configure buckets" — a histogram with only describe_histogram! and no
// Matcher::Full gets default [0.005..10.0] buckets. For count-type or
// long-duration metrics, every sample lands in +Inf and p99 is unusable.
// This caught rio_scheduler_build_graph_edges (P0321): described, emitted,
// spec'd with suggested buckets — but init_metrics had no Matcher for it.
#[test]
fn all_histograms_have_bucket_config() {
    use rio_common::observability::HISTOGRAM_BUCKET_MAP;

    // Histograms that genuinely fit [0.005..10.0]. See the
    // HISTOGRAM_BUCKET_MAP doc comment for the rationale on each.
    const DEFAULT_BUCKETS_OK: &[&str] = &[
        "rio_scheduler_recovery_duration_seconds",
        // Actor commands should be sub-second; the [0.005..10.0]
        // default covers the "alert at p99>1s" range exactly. A
        // command at 10s+ is already a head-of-line stall (I-140) —
        // the +Inf bucket is the alert, finer resolution above 10s
        // doesn't change the response.
        "rio_scheduler_actor_cmd_seconds",
    ];

    assert_histograms_have_buckets(
        rio_scheduler::describe_metrics,
        HISTOGRAM_BUCKET_MAP,
        DEFAULT_BUCKETS_OK,
        "rio-scheduler",
    );
}
